README.md

The default configuration file was renamed to `ng-package.json`. Reflect these changes in the readme.
BREAKING CHANGE:  the default config file is renamed from `.ng-packagr.json` to `ng-package.json`. Use one `ng-package.json` per each Angular library project.

feat: default config file `ng-package.json`

---

lib/model/ng-package.ts
lib/steps/ngc.ts

Fixes an AoT import error when metadata.json files include an "importAs" property.

fix: set flatModuleId to the name from package.json

---

integration/sample_core/specs/metadata.ts
integration/sample_custom/specs/metadata.ts
integration/sample_custom/specs/package.ts
integration/sample_custom/specs/typings.ts
integration/sample_material/specs/metadata.ts
integration/sample_material/specs/package.ts
integration/sample_material/specs/typings.ts

Tests assert correct packaging with folder structure from material design.
Also, refactor the other tests so that failures file reading files are reported in before hook, allowing other tests to still run.

test: specs for `@sample/material`

---

integration/sample_core/src/angular.service.ts
lib/steps/rollup.ts

Fixes the following BUILD ERROR
'ReplaySubject' is not exported by node_modules\rxjs\ReplaySubject.js
Error: 'ReplaySubject' is not exported by node_modules\rxjs\ReplaySubject.js

fix: add `rxjs/ReplaySubject` to rollup defaults

---

integration/sample_core/ng-package.json
integration/sample_core/src/angular.service.ts
lib/model/ng-package.ts
lib/ng-packagr.ts
lib/steps/rollup.ts

feat: lib.externals support.

---

integration/build.js
integration/sample_typings/ng-package.json
integration/sample_typings/package.json
integration/sample_typings/public_api.ts
integration/sample_typings/src/validate-commit-msg.d.ts
integration/sample_typings/src/validator.ts
package.json
tsconfig.json

Motivation: sometimes, we have 3rd party dependencies that ship w/o type definitions. Maybe, we don't have type definitions at DefinetlyTyped and so we have to write our own. Since ng-packagr auto-generates our tsconfig, we have to import custom type definitions via triple-slash reference.
This change adds a sample library to the integration tests, making this a legimitate and desired feature which needs to be supported.

test: library w/ custom typings

---

lib/steps/assets.ts

As mentioned in #51 by @ChrisProlls in his [comment](https://github.com/dherges/ng-packagr/issues/51#issuecomment-307148324), we're unable to specify a source folder apart from the package.json file.
So we have to exclude the node_modules folder and the typings from the template glob.

removed node_modules, excluded typings

---

lib/steps/assets.ts

Motivation: In certain use cases, autoprefixer and browserslist ended up looking up an `undefined` path since postcss explicitly sets plugin options, thus overwriting a file path to `undefined`.
[debug] processAssets ng-packaged/my-lib to ng-packaged/.ng_build/ts
[debug] render stylesheet ng-packaged/my-lib/src/foo/foo.component.scss
[debug] rendering sass for ng-packaged/my-lib/src/foo/foo.component.scss
[debug] postcss with autoprefixer for ng-packaged/my-lib/src/foo/foo.component.scss
BUILD ERROR
Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined
at assertPath (path.js:7:11)
at Object.resolve (path.js:1146:7)
at eachParent (ng-packaged/node_modules/ng-packagr/node_modules/browserslist/index.js:65:18)
at getStat …

fix: pass file pathes to `postcss.process()`

---

package.json
src/lib/steps/rollup.ts
yarn.lock

This PR is to fix an issue that is described in the [issue #227](https://github.com/rollup/rollup-plugin-commonjs/issues/227).

fix: add rollup commonjs plugin to support all library types

---

.gitignore
src/lib/util/copy.ts
src/lib/util/fs.ts
src/lib/util/json.ts
src/lib/util/promisify.ts
src/lib/util/rimraf.ts

- Existing tests should cover the changes.
Fix for #126

fix(#126): Properly handle rejected promises in utils

---

src/lib/bundler.ts
src/lib/model/ng-package.ts
src/lib/ng-packagr.ts
src/lib/steps/package.ts

Serves a step towards secondary entrypoints.
Extract Angular bundling for `(entryFile: string) => { module, main, ..}`. Step towards secondary entrypoints.

refactor: extract Angular bundling process

---

integration/consumer.sh
package.json

Motivation: integration testing from a consumer's point of view.
Assert that importing the generated libraries in an `ng` cli app produces build success.
Details:
- adds a `ng` CLI app
- `yarn link` sample libraries to CLI app
- build the CLI app in several ways:
- `ng build --target development` (dev w/o AoT)
- `ng build --target production` (prod w/o AoT)
- `ng build --target production --aot` (prod w AoT)

ci: include `ng` cli consumer build in test script

---

README.md
integration/samples/core/ng-package.json
integration/samples/custom/ng-package.json
integration/samples/externals/ng-package.json
integration/samples/material/ng-package.json
integration/samples/package-json/package.json
integration/samples/typings/ng-package.json
src/package.schema.json

```
[ ] Bug Fix
[x] Feature
```
See review discussions in #169
By referencing `$schema: "./node_modules/ng-packagr/package.schema.json"` in a `package.json` you get JSON editing support for the custom `ngPackage` property in an IDE.
```json
{
"$schema": "./node_modules/ng-packagr/package.schema.json",
/* .. */
}
```
```
[ ] Yes
[x] No
```

feat: add json schema for `package.json` with custom `ngPackage` property

---

README.md
integration/samples/secondary/should-be-ignored/bar/bar.component.html
integration/samples/secondary/should-be-ignored/bar/bar.component.scss
integration/samples/secondary/should-be-ignored/bar/bar.component.ts
integration/samples/secondary/should-be-ignored/index.ts
integration/samples/secondary/should-be-ignored/package.json
integration/samples/secondary/specs/package.ts
src/lib/steps/package.ts

```
[x] Bug Fix
[ ] Feature
```
This should fix #213
Now the ngPackage field is required in a package.json in order to be considered a secondary package.
```
[ ] Yes- would be yes if the RC releases are considered, otherwise...
[x] No
```

fix: prevent BUILD ERROR if unrelated package.json exists in a sub-folder

---

package.json
src/lib/util/json.ts
yarn.lock

```
[x] Bug Fix
[ ] Feature
```
Previously, a user of ng-packagr could install an incompatible typescript version for ng-packagr. Prevent inadvertent typescript installs by depending on a user's typescript isntallation (peerDependencies). Same for tsc-wrapped.
```
[ ] Yes
[x] No
```

fix: depend on user's typescript and tsc-wrapped

---

integration/samples/core/specs/bundle.ts
integration/samples/secondary/specs/bundle.ts
src/lib/bundler.ts
src/lib/model/ng-package-data.ts

```
[x] Bug Fix
[ ] Feature
```
This PR changes the UMD module name of libraries to include the scope name. See #251 for background information on this change.
```
[x] Yes
[ ] No
```
Yes, this is a breaking change for users that have published libraries before. This change causes new builds to get assigned a different module name if a scope is being used.

fix: include scope name in module name of Rollup bundle

---

package.json
src/lib/steps/assets.ts
yarn.lock

```
[ ] Bug Fix
[x] Feature
```
Uses 'node-sass-tilde-importer'  to resolve imports during scss transformation. See https://www.npmjs.com/package/node-sass-tilde-importer
Resolves #346
```
[ ] Yes
[x] No
```

feat: resolve "~" scss import statements to nearest `node_modules`

---

integration/samples/core/specs/sourcemaps.ts
src/lib/conf/tsconfig.ngc.json

tslib helpers will not be emitted in the JavaScript output. Rollup will inline required helpers only once in a bundle file. Results in smaller bundle files.
```
[ ] Bug Fix
[x] Feature
```
Closes #337
```
[ ] Yes
[x] No
```

feat: enable tslib `importHelpers` by default

---

integration/samples/core/specs/sourcemaps.ts
package.json
src/cli/main.ts
src/lib/entry-point-transforms.ts
src/lib/steps/ngc.ts
src/lib/util/ngc-patches.ts
src/lib/util/ts-transformers.ts

```
[x] Bug Fix
[ ] Feature
```
ng-packagr misses to run tsickle on the generated JavaScript output, even if `annotateForClosureCompiler: true` is set. Register the emit callback for `ngc` 
```
[ ] Yes
[x] No
```

fix: set ngc emit callback for `tsickle`  processing

---

src/lib/steps/assets.ts

```
[x] Bug Fix
[ ] Feature
```
when the sass inline fails it shows that it failed in `Object object` when it should tell you which file failed.. this is because its not getting the proper variable that contains the filePath
```
[ ] Yes
[x] No
```

fix(): show proper path of failure on sass inline

---

integration/samples/custom/src/foo-bar/foo-bar.component.html
integration/samples/custom/src/foo-bar/foo-bar.component.ts

```
[ ] Bug Fix
[ ] Feature
```
Reproduces the issues faced with `ts.NodeFlags.Synthesized` in clarity's (and other's) build.
ngc/tsc failed for:
- visiting constructor parameters of a class with a synthesized decorator
- visiting members of a class with a synthesized decorator
See #369
```
[ ] Yes
[x] No
```

test: reproduce `ts.NodeFlags.Synthesized` issues

---

integration/consumers/ng-cli/package.json
integration/consumers/ng-cli/yarn.lock
package.json
yarn.lock

```
[ ] Bug Fix
[x] Feature
```
- removed `lodash`, `glob` and `read-file` from dependencies
- removed `@types/glob`, `@types/lodash` from `devDependencies`
- bumped `@angular/cdk`, `tsickle` and `typescript`
- updated `peerDependencies` `tsickle` to `^0.25.0` and `typescript` to `>=2.4.2 <2.6`
```
[ ] Yes
[x] No
```

feat: remove unused `dependencies` and update `peerDependencies`

---

.vscode/launch.json
integration/samples.dev.js
package.json
scripts/postbuild.js
scripts/prepublish.js
src/lib/util/ts-transformers.spec.ts
src/lib/util/ts-transformers.ts
src/tsconfig.packagr.json
src/tsconfig.specs.json
yarn.lock

```
[ ] Bug Fix
[ ] Feature
```
Allows non-call expression decorators in typescript parsing.
```ts
@Component({})
@Other
class Component {}
```
```
[ ] Yes
[x] No
```

fix: relax on non-call-expression decorators in typescript parsing

---

.vscode/launch.json
README.md
integration/samples.sh
integration/samples/package-js/README.md
integration/samples/package-js/baz/baz.component.ts
integration/samples/package-js/build.dev.js
integration/samples/package-js/index.ts
integration/samples/package-js/ng-package.js
integration/samples/package-js/package.json
integration/samples/package-js/secondary/baz/baz.component.ts
integration/samples/package-js/secondary/index.ts
integration/samples/package-js/secondary/ng-package.js
integration/samples/package-js/secondary/package.json
integration/samples/package-js/secondary/ui-lib.module.ts
integration/samples/package-js/specs/package.ts
integration/samples/package-js/ui-lib.module.ts
src/lib/steps/init.ts

```
[ ] Bug Fix
[x] Feature
```
Discovery of primary and secondary entry points have been changed to the following;
- `package.json`: with `ngPackage` property
- `ng-package.json` (requires a `package.json` as sibling)
- `ng-package.js` (default export, requires a `package.json` as sibling)
Closes: #190
```
[ ] Yes
[x] No
```

feat: discover entry points from user configuration

---

package.json

```
[ ] Bug Fix
[ ] Feature
```
`test:specs` is not being run when invoking `test` in ci
```
[ ] Yes
[x] No
```

build: invoke `test:specs` when running the `test` script

---

src/lib/domain/ng-package-format.ts
src/ng-package.schema.json

```
[ ] Bug Fix
[x] Feature
```
No tests added. Tests were unchanged.
***BREAKING CHANGES:*** Setting `ngPackage.src` has no effect any more. The source directory (base path) is equivalent to the location of the (primary) `ng-package.json`, `package.json`, or `ng-package.js`.
```
[x] Yes
[ ] No
```

feat: remove `src` property from package schema

---

integration/consumers/tsc/src/jsx-consumer/jsx-consumer.component.ts
integration/consumers/tsc/src/main.ts
integration/consumers/tsc/tsconfig.json

```
[x] Bug Fix
[ ] Feature
```
So I think that the reason these tests weren't passing before was due to the refactor making the `paths` in `tsconfig` out of date, they needed one else `../`. Then I ran into a class of issues that's described in these GitHub issues while running `yarn run integration:consumer:ngc`:
https://github.com/angular/vscode-ng-language-service/issues/183
https://github.com/angular/angular/issues/16382
I fixed that issue by changing `baseUrl` to be `./` and now when I run `yarn run integration:consumer:ngc` I don't get any errors.
Sorry it took me so long to get to this @dherges!
```
[ ] Yes
[x] No
```

Fix Jsx Integration Test

---

src/lib/steps/rollup.spec.ts
src/lib/steps/rollup.ts

Required change for rollup 0.53
```
[x] Bug Fix
[ ] Feature
```
Blocks #438
```
[ ] Yes
[x] No
```

fix: remove moduleId from rollup bundle options

---

integration/consumers.sh
integration/consumers/ng-cli/package.json
integration/consumers/ng-cli/src/app/app.module.ts
integration/consumers/ng-cli/src/app/cdk/cdk.module.ts
integration/consumers/ng-cli/src/app/secondary/secondary.module.ts
integration/consumers/ng-cli/yarn.lock
integration/samples/secondary/package.json
integration/samples/secondary/specs/bundle.ts
integration/samples/secondary/specs/es2015-api.ts
integration/samples/secondary/specs/es5-api.ts
integration/samples/secondary/specs/metadata.ts
integration/samples/secondary/specs/package.ts
integration/samples/secondary/specs/umd.ts

```
[ ] Bug Fix
[ ] Feature
```
Added integration test. Angular CLI app depends on `@sample/secondary` and `@sample/secondary/sub-module`. Verifies that secondary entry points are resolved in consumer app.
```
[ ] Yes
[x] No
```

test: depend on `@sample/secondary` in Angular CLI app

---

src/lib/util/ts-transformers.ts

```
[x] Bug Fix
[ ] Feature
```
This change will allow parsing and extracting styles from components that list multiple styleUrls (or that have a trailing comma on a single item)
For some reason the text returned by `node.getChildren().map(n => n.getText())` was including the comma delimiter for the array entries.
Addresses issues:
- #407 
- #424 
No, I don't presume any adverse side effects from this, since it's hard to foresee a future where commas aren't used to separate array entries.

fix: supports extracting styles from multiple styleUrls

---

.vscode/launch.json
package.json
src/lib/commands/build.command.ts
src/lib/commands/command.ts
src/lib/commands/version.command.ts
src/lib/ng-v5/packagr.spec.ts
src/lib/ng-v5/packagr.ts
src/public_api.ts
yarn.lock

```
[ ] Bug Fix
[x] Feature
```
Add `@stable` annotations to the command API.
Adds [`injection-js`](https://github.com/mgechev/injection-js) and [`rxjs`](https://github.com/ReactiveX/rxjs/tree/master/src) to dependencies of ng-packagr.
A step towards customizing through dependency injection. Future usage example:
```ts
ngPackagr()
.withProviders([
{
provide: TSCONFIG_DEFAULTS,
deps: [PROJECT_TOKEN],
useFactory: (project: string) => {
return { /* ... customize tsconfig for this verify specific project (?!?) */ };
}
}
])
.build();
```
```
[ ] Yes
[x] No
```

feat: stabilize command API, step towards customizing through DI

---

README.md
docs/DESIGN.md
integration/samples/language-level/ng-package.json
integration/samples/language-level/package.json
integration/samples/language-level/public_api.ts
integration/samples/language-level/src/angular.component.ts
integration/samples/language-level/src/angular.module.ts
src/lib/ng-package-format/entry-point.ts
src/lib/steps/ngc.ts
src/ng-package.schema.json

```
[ ] Bug Fix
[X] Feature
```
This PR addresses https://github.com/dherges/ng-packagr/issues/354
From the issue:
Current Behaviour: language level is tied to es2015
Desired use case is es2016 / es2017 language level support for authors writing library code with es2016 features.
**Expected Behaviour**
Usage: `ngPackage.lib.languageLevel = "es2017"`
Internal / implementation detail: `tsconfig compilerOptions.lib = [ /*..*/ es2017 /*..*/ ]`
**Version Information**
```
ng-packagr: v2.0.0-rc.x
```
```
[ ] Yes
[X] No
```

feat: add language level support for library authors

---

README.md
integration/samples/scss-paths/.browserslistrc
integration/samples/scss-paths/README.md
integration/samples/scss-paths/assets/theme.scss
integration/samples/scss-paths/baz/baz.component.html
integration/samples/scss-paths/baz/baz.component.scss
integration/samples/scss-paths/baz/baz.component.ts
integration/samples/scss-paths/package.json
integration/samples/scss-paths/public_api.ts
integration/samples/scss-paths/specs/metadata.ts
integration/samples/scss-paths/sub-module/.browserslistrc
integration/samples/scss-paths/sub-module/README.md
integration/samples/scss-paths/sub-module/assets/common.scss
integration/samples/scss-paths/sub-module/bar/bar.component.html
integration/samples/scss-paths/sub-module/bar/bar.component.scss
integration/samples/scss-paths/sub-module/bar/bar.component.ts
integration/samples/scss-paths/sub-module/index.ts
integration/samples/scss-paths/sub-module/package.json
integration/samples/scss-paths/sub-module/ui-lib.module.ts
integration/samples/scss-paths/ui-lib.module.ts
src/lib/ng-package-format/entry-point.ts
src/lib/steps/assets.ts
src/ng-package.schema.json

```
[ ] Bug Fix
[X] Feature
```
Updates to the configuration under the `lib` element to add a new `sassIncludePaths` option, which takes an array of paths that will be used to resolve SCSS `@import` statements by the SASS compiler. If the paths are not absolute, they will be resolved relative to the ngPackage configuration file.
* Updated ng-package.schema.json to include the new option.
* Updated NgEntryPoint to read the property and resolve URLs relative to the package.
* Updated the assets step to pass the included paths to the SASS compiler.
* Added a new scss-paths integration test suite to ensure the SASS imports are working properly.
* …

feat: adding implementation and tests for resolving scss include paths

---

package.json
src/lib/steps/assets.ts
yarn.lock

```
[x] Bug Fix
[ ] Feature
```
Removes comments from processed stylesheets. Also fixes #503 since if back ticks were in stylesheets, it broke builds. See #503 for more details.
```
[ ] Yes
[x] No
```

fix: strip comments from processed stylesheets

---

src/lib/ng-package-format/artefacts.ts
src/lib/steps/entry-point-transforms.ts
src/lib/steps/ngc.ts
src/lib/ts/ng-component-transformer.ts
src/lib/ts/synthesized-compiler-host.ts
src/lib/ts/transform-component.ts

```
[x] Bug Fix
[ ] Feature
```
Tests unchanged. Specs should be green, so considered to be non-breaking.
Beside, re-write the `transformComponent` and `ComponenTransformer` APIs. They might become public.
```
[ ] Yes
[x] No
```

fix: dispose the previous TransformationResult after inlining

---

integration/samples/custom/specs/metadata.ts
integration/samples/material/specs/metadata.ts
integration/samples/scss-paths/specs/metadata.ts
src/lib/steps/assets.ts

```
[x] Bug Fix
[ ] Feature
```
fix: css comments should be discarded irrespective of `cssUrl`

fix: css comments should be discarded irrespective of `cssUrl`

---

package.json
src/lib/ng-v5/entry-point/resources/stylesheet.transform.ts
src/lib/ng-v5/entry-point/resources/template.transform.ts

```
[x] Bug Fix
[ ] Feature
```
fix: strip BOM from processed assets (#487)
use [strip-bom](https://github.com/sindresorhus/strip-bom) package to remove byte order mark from the string of processed assets, and add it to dependencies in package.json
```
[ ] Yes
[x] No
```

fix: strip bom from processed assets (#487)

---

integration/samples/core/specs/es2015-api.ts
integration/samples/core/specs/umd.ts
package.json
src/lib/flatten/flatten.ts
src/lib/flatten/tsc.ts
src/lib/ng-v5/entry-point/write-package.transform.ts
yarn.lock

```
[x] Bug Fix
[ ] Feature
```
In a nutshell
- tslib should be embeeded in UMD
- tslib should be external for ESM5 modules
- No tslib for ESM2015
- add tslib as a dependency in package,json, this is important as without this the consumer will break unless there is another library that uses tslib
Closes: #371
```
[ ] Yes
[x] No
```

fix: embed `tslib` helpers in UMD bundles only

---

package.json
src/lib/flatten/flatten.ts
src/lib/flatten/rollup.ts
src/lib/ng-v5/entry-point/ts/analyse-sources.transform.ts
yarn.lock

```
[x] Bug Fix
[ ] Feature
```
Updates rollup.
Closes #488, #523 
```
[ ] Yes
[x] No
```

fix: update rollup to ^0.55.0

---

src/lib/ng-v5/entry-point/resources/stylesheet.transform.ts
src/lib/util/json.ts

```
[ ] Bug Fix
[ ] Feature
```
Minor thing
An async function always wraps the return value in a Promise. Using return await just adds extra time before the overreaching promise is resolved without changing the semantics
```
[ ] Yes
[x] No
```

perf: don't await and return

---

integration/samples/typings/specs/typings.ts
src/lib/ng-package-format/entry-point.ts
src/lib/ng-v5/entry-point/ts/compile-ngc.transform.ts
src/lib/ng-v5/entry-point/write-package.transform.ts
src/lib/ngc/compile-source-files.ts
src/lib/ts/redirect-write-file-compiler-host.ts
src/lib/ts/tsconfig.ts

```
[x] Bug Fix
[ ] Feature
```
Used to work in 2.0.0-rc.4
Broke in rc5 and later
```
[ ] Yes
[x] No
```

fix: write type definition files (via triple-slash reference) to npm package

---

src/lib/brocc/transform.di.ts
src/lib/commands/build.command.ts
src/lib/commands/command.ts
src/lib/commands/version.command.ts
src/lib/deprecations.ts
src/lib/ts/ng-component-transformer.spec.ts
src/lib/ts/ng-component-transformer.ts
src/lib/ts/transform-component.ts
src/public_api.spec.ts
src/public_api.ts
src/testing/typescript.testing.ts
src/testing/typesript.testing.spec.ts

```
[ ] Bug Fix
[x] Feature
```
Arrange the public API surface for programmatic usage.
```ts
import { ngPackagr, /* .. */ } from 'ng-packagr';
```
See the `public_api.ts` for the list of exported symbols.
```
[ ] Yes
[x] No
```

feat: export and test public api surface

---

src/lib/ts/ng-type-guards.spec.ts
src/lib/ts/ng-type-guards.ts

```
[x] Bug Fix
[ ] Feature
```
Recognize component decorator metadata for named, aliased imports and namespace imports.
Usage Examples:
```ts
import { Component as Foo } from '@angular/core';
@Foo({
selector: 'foo',
template: `<h1>He yo, I am from a named, aliased import</h1>`
})
export class FooComponent {}
```
```ts
import * as ngCore from '@angular/core';
@ngCore.Component({
selector: 'foo',
template: `<h1>He yo, I am from a namespace import</h1>`
})
export class FooComponent {}
```
```
[ ] Yes
[x] No
```

fix: recognize aliased and namespace decorator imports

---

integration/samples/core/specs/es5-api.ts
src/lib/flatten/flatten.ts
src/lib/flatten/rollup.ts
src/lib/flatten/tsc.ts

Closes: #587
```
[x] Bug Fix
[ ] Feature
```
Cherry pick tslib methods and avoid having multiple imports for tslib
```
[ ] Yes
[x] No
```

fix: multiple import statements for `tslib`

---

README.md
integration/samples/scss-paths/assets/theme.less
integration/samples/scss-paths/assets/theme.styl
integration/samples/scss-paths/baz/baz.component.html
integration/samples/scss-paths/baz/baz.component.less
integration/samples/scss-paths/baz/baz.component.styl
integration/samples/scss-paths/baz/baz.component.ts
integration/samples/scss-paths/specs/metadata.ts
integration/samples/scss-paths/sub-module/assets/common.less
integration/samples/scss-paths/sub-module/assets/common.styl
integration/samples/scss-paths/sub-module/bar/bar.component.less
integration/samples/scss-paths/sub-module/bar/bar.component.styl
integration/samples/scss-paths/sub-module/bar/bar.component.ts
integration/samples/scss-paths/sub-module/package.json
src/lib/ng-package-format/entry-point.ts
src/lib/ng-v5/entry-point/resources/stylesheet.transform.ts
src/ng-package.schema.json

```
[ ] Bug Fix
[X] Feature
```
Updating the ng-package.json file to include a more generic option that also supports resolving Less and Stylus import paths to achieve feature parity with `@angular/cli`.
- Added styleIncludePaths option in ng-package.schema.json
- Updated README.md to refer to the new option name
- Updated entry-point.ts to use the new option (also uses older sassIncludePaths for backwards compatability).
- Updated stylesheet.transform.ts to pass the include paths to the Less and Stylus compilers.
- Updated the integration tests for scss-paths to also include tests for Less and Stylus
This should resolve the comments about …

feat: `styleIncludePaths` for feature parity with Angular CLI

---

src/lib/ts/synthesized-compiler-host.ts

```
[X] Bug Fix
[ ] Feature
```
This change passes 'setParentNodes' when calling 'createCompilerHost' as part of the "synthesized" compiler host wrapper.
This resolves an issue we have encountered with `compiler-cli` when it processes `SourceFile` objects
created by this wrapped CompilerHost, caused by the `parent` reference not being set on all AST nodes in the `SourceFile`:
```
TypeError: Cannot read property 'text' of undefined
at TokenObject.TokenOrIdentifierObject.getText (node_modules\typescript\lib\typescript.js:90769:57)
at Evaluator.evaluateNode (node_modules\@angular\compiler-cli\src\metadata\evaluator.js:604:66)
...
```
```
[ ] Yes …
```

fix: pass 'setParentNodes' when calling 'createCompilerHost'

---

integration/samples/custom/specs/metadata.ts
integration/samples/material/specs/metadata.ts
integration/samples/scss-paths/specs/metadata.ts
package.json
src/lib/ng-v5/entry-point/resources/stylesheet.transform.ts
src/lib/ng-v5/entry-point/resources/template.transform.ts
yarn.lock

```
[ ] Bug Fix
[x] Feature
```
At that moment, `css` and `html` within components cannot be optimized by the consumers by using `Webpack`, `Angular Build Optimizer` or any other tool that bundles simply because these optimization have to happen at a library level when the the transformation happens that turns these assets into strings in the `JS` file
Reduce final bundle size by;
- Using `cleanCss` this will remove comments, new lines, extra quotes among others
- Remove new lines in `HTML` templates as these don't have any effect in the browser
Other component libraries are doing the same. Apart from `preserveWhitespaces` (Which in this case …

feat: reduce library bundle size by clean-css

---

integration/samples/keep-output-path/.gitignore
integration/samples/keep-output-path/dest/file.txt
integration/samples/keep-output-path/ng-package.json
integration/samples/keep-output-path/package.json
integration/samples/keep-output-path/specs/keep-file.ts
integration/samples/keep-output-path/src/public_api.ts
src/lib/ng-package-format/package.ts
src/lib/ng-v5/package.transform.ts
src/ng-package.schema.json

```
[ ] Bug Fix
[x] Feature
```
Provide an option for users to not delete output path before build. The name was choosen for feature parity with NG CLI.
Closes: #632
```
[ ] Yes
[x] No
```

feat: add `deleteOutputPath` option

---

package.json
yarn.lock

```
[x] Bug Fix
[ ] Feature
```
Locks rollup-plugin-commonjs at 8.3.0 because of #657 
```
[ ] Yes
[x] No
```

fix: lock rollup-plugin-commonjs dependency at 8.3.0, refs #657

---

integration/samples/core/specs/package.ts
integration/samples/core/specs/ts-api.ts
integration/samples/custom/ng-package.json
integration/samples/custom/specs/package.ts
src/lib/ng-package-format/entry-point.ts
src/lib/ng-package-format/package.ts
src/lib/ng-v5/entry-point/write-package.transform.ts
src/ng-package.schema.json

```
[x] Bug Fix
[ ] Feature
```
See #686
Configuration location is:
```json
{
"name": "@foo/bar",
"ngPackage": {
"keepLifecycleScripts": true,
"lib": {
/* .. things related to source code and bundle files .. */
}
}
}
```
```
[ ] Yes
[x] No
```

fix: move `keepLifecycleScripts` to ngPackage conf

---

README.md

```
[ ] Bug Fix
[ ] Feature
```
On Line 302 of README.md: 
- "budles" is misspelled => "bundle."
- Proper phrasing would be "in your bundled files." instead of "on your bundles."
```
[ ] Yes
[x] No
```

docs(readme): fix spelling error and phrasing 

---

package.json

```
[ ] Bug Fix
[x] Feature
```
I did some basic testing using `ng-packagr` with Angular 6 and it seemed to be ok.
What I did was:
- use `@angular/{compiler,compiler-cli}@6.0.0-rc.0`
- build a library with a ngmodule, component and service
- consume the library (via tsconfig paths to build artifacts) in a Angular app using `6.0.0-rc.0`, using the component and service
- serve the app in JIT and AOT modes,
- check the build for errors (saw none)
- check the served app in the browser for the component and service (were there)
```
[ ] Yes
[x] No
```

feat: allow Angular 6 as a peer dependency

---

integration/samples.sh
integration/samples/failures/index.ts
integration/samples/failures/package.json
integration/samples/failures/specs/non-peer-deps.ts
package.json
src/lib/ng-package-format/package.ts
src/lib/ng-v5/entry-point/write-package.transform.ts
src/ng-package.schema.json

```
[x] Bug Fix
[ ] Feature
```
Publish npm packages with `dependencies` and/or `devDependencies` easily leads to installing multiple versions of a dependency to an application's `node_modules` folder. While this is a desirable solution on server-side or standalone programs, it's a source for bugs on front-end build stacks and UI technologies – you don't want to install two different versions of Angular, don't you?!
A motivation [why `peerDependencies` are the preferred solution for libraries](https://blog.domenic.me/peer-dependencies/) can be found on the Hidden Variables blog (the article is also cross-posted on the npm blog).
With this …

fix: validate non-peerDependencies at build time

---

src/lib/flatten/uglify.ts

```
[ ] Bug Fix
[ ] Feature
```
- JS map and content files can be read in parallel.
- `sourceMap` map content is expected to be a JSON object.
```
[ ] Yes
[x] No
```

perf: read content and map `async` in `minifyJsFile`

---

src/lib/ng-v5/entry-point/write-package.transform.ts

Minor wording/spelling change to fix "peerDependencies" spelling in the warning output message.
```
[ ] Bug Fix
[ ] Feature
[ x ] Other (Refactoring, Added tests, Documentation, ...)
```
This is a minor change for the spelling of the peerDependencies.
```
[ ] Yes
[ x ] No
```

fix: naming of warning for adding peerDependencies to package.json

---

src/tsconfig.packagr.json

```
[ ] Bug Fix
[ ] Feature
```
This is a node library and thus DOM is not needed
```
[ ] Yes
[ ] No
```

build: remove `DOM` from tsconfig

---

integration/samples/apf/specs/package.ts
integration/samples/core/package.json
integration/samples/core/specs/package.ts
src/lib/ng-package-format/entry-point.ts
src/lib/ng-v5/entry-point/write-package.transform.ts

```
[ ] Bug Fix
[x] Feature
```
By default, ng-packagr will apply the `"sideEffects": false` flag to the distribution-ready `package.json` files.
To disable the behaviour, users need to set `"sideEffects": true` in their source `package.json` files explicitly.
Adding the flag is recommended in Angular Package Format v6. More information:
> webpack v4 "sideEffects": false
> 
> As of webpack v4, packages that contain a special property called "sideEffects" set to false in their package.json, will be processed by webpack more aggressively than those that don't. The end result of these optimizations should be smaller bundle size and better code …

feat: add `"sideEffects": false` flag to dist-ready package.json

---

src/lib/flatten/umd-module-id-strategy.spec.ts
src/lib/flatten/umd-module-id-strategy.ts

```
[X] Bug Fix
[ ] Feature
```
At the moment `@angular/common/http/testing` UMD module id is being generated as `ng.common.http/testing` which is not correct as it should be `ng.common.http.testing`
https://unpkg.com/@angular/common@5.2.10/bundles/common-http-testing.umd.js
```
[ ] Yes
[X] No
```

fix: incorrect `UMD` module id for `@angular/common/http/testing`

---

CHANGELOG.md

As the creation of a tarball was droped (by choice) by #738, this commit
add the associated missing breaking change informations in CHANGELOG.
```
[ ] Bug Fix
[ ] Feature
```
see #802
```
[ ] Yes
[x] No
```

docs: add tarball creation informations

---

src/lib/ngc/compile-source-files.ts

```
[x] Bug Fix
[ ] Feature
```
If the consumer doesn't pass `flatModuleId` and `flatModuleOutFile` the emitFlag will be incorrect and the metadata file won't be flattened, even though these properties are later set by `ng-packagr`. Rely on `ngc` to set the proper emit flag based on the tsconfig options.
/cc @filipesilva  @dherges 
And thanks @filipesilva for highlighting this up and sorry for the inconvenience.
Relates to: https://github.com/angular/devkit/pull/794
```
[ ] Yes
[X] No
```

fix: don't pass `emitFlags` leave it up to `ngc`

---

src/lib/ts/tsconfig.ts

```
[x] Bug Fix
[ ] Feature
```
Set the "declaration" option to true by default (not overriding in order to keep to right error message).
Related issue : when building (with angular-cli --project mylib) with a custom tsConfig file, the following error occur at ngc step :
```
BUILD ERROR
error TS5052: Option 'declarationDir' cannot be specified without specifying option 'declaration'.
Error: error TS5052: Option 'declarationDir' cannot be specified without specifying option 'declaration'.
at Object.<anonymous> (D:\git\myproj\web\js\node_modules\ng-packagr\lib\ngc\compile-source-files.js:62:68)
at Generator.next (<anonymous>)
at …
```

fix: missing 'declaration' option in tsconfig

---

src/lib/brocc/depth.spec.ts
src/lib/brocc/depth.ts

```
[X] Bug Fix
[ ] Feature
```
Fixes an issue that can occur in a library using multiple secondary entry-points that depends on each other if the dependencies are not parsed in a "correct" order.
The added unit test will, without the fix, throw the following exception:
>   1) DepthBuilder
should group an unordered complex scenario:
TypeError: Cannot read property 'push' of undefined
at /workspace/src/lib/brocc/depth.ts:106:22
at Map.forEach (<anonymous>)
at DepthBuilder.build (src/lib/brocc/depth.ts:105:16)
at Context.<anonymous> (src/lib/brocc/depth.spec.ts:64:28)
Logging the `nodeDepths` map reveals the following incorrect depth analysis: …

fix: Depth analysis of unordered dependencies

---

integration/samples/secondary/feature-c/feature-c.ts
integration/samples/secondary/feature-c/package.json
src/lib/brocc/depth.spec.ts
src/lib/brocc/depth.ts

```
[x] Bug Fix
[ ] Feature
```
- [] Tests for the changes have been added
This will fix an error that appears only when using multiple secondary entry-points depending on each other.
Updated the examples to cause the error and fixed it with a proper initialization of the involved array holding our buckets. I'm not able to create a test for this scenario and think the samples will cover it properly.
That's the error it will fix:
```
Cannot read property 'push' of undefined
TypeError: Cannot read property 'push' of undefined
at nodeDepths.forEach (/Users/geokal/job/opensource/ng-packagr/src/lib/brocc/depth.ts:107:22)
```
```
[ ] Yes
[x] No
```

fix: create an array large enough to hold all buckets

---

src/lib/ng-v5/entry-point/ts/compile-ngc.transform.ts

```
[x] Bug Fix
[ ] Feature
```
In #826 the option was enabled in tsconfig.ngc.json and then in #812 the option was disabled again when downleveling to ES5. This then causes #822 to resurface again, which was supposedly fixed by #826.
No integration test has been added at this moment, I'm hoping this can get in during the RCs to get real world feedback if the function calls in decorator bugs are now actually fully resolved. With the changes in this PR applied to 3.0.0-rc4 I have been able to successfully build my project that was also suffering from this issue after upgrading from 2.4 to the 3.0 RC.
After some two hour debug session in the …

fix: do not disable fullTemplateTypeCheck when ES5 downleveling

---

integration/samples/apf/specs/package.ts
src/lib/ng-package-format/entry-point.ts
src/lib/ng-v5/entry-point/write-package.transform.ts
src/tsconfig.packagr.json

```
[] Bug Fix
[x] Feature
```
`tslib` dependency is only needed at entry point level.
```
[ ] Yes
[x] No
```

 feat: don't add dependency to `tslib` in secondary entrypoints

---

integration/samples/apf/specs/files.ts
src/lib/ng-v5/entry-point/write-package.transform.ts

```
[x] Bug Fix
[ ] Feature
```
This bug was introduced with https://github.com/dherges/ng-packagr/pull/862
Basically declarations are being copied twice.
```
[ ] Yes
[x] No
```

fix: remove duplicate declarations under `dist`

---

src/lib/brocc/node.ts
src/lib/ts/redirect-write-file-compiler-host.ts
src/lib/ts/transform-component.ts

```
[x] Bug Fix
[ ] Feature
```
- [] Tests for the changes have been added
To small refactors and fix noticed while implementing watch / incremental builds.
1) refactor: redirectWriteFileCompilerHost call original `writeFile`
2) refactor: skip transformation for `ngfactory` and `ngstyle`
3) fix: `dependsOn` appends instead of replacing 
When a node has the same `url` instead of replacing the node it appends to the `array`. As at the moment filtering is based on object equality
8612cb5
```
[ ] Yes
[x] No
```

Refactors and fixes

---

integration/samples/material/ui-lib.module.ts
package.json
src/lib/ng-v5/entry-point/ts/compile-ngc.transform.ts
yarn.lock

```
[ ] Bug Fix
[ ] Feature
```
This is not needed for downleveling type checking can be skipped altogether.. 
https://github.com/dherges/ng-packagr/pull/860
```
[ ] Yes
[x] No
```

perf: remove extra template type checking for downleveling

---

src/lib/flatten/umd-module-id-strategy.spec.ts
src/lib/flatten/umd-module-id-strategy.ts

```
[x] Bug Fix
[x] Feature
```
Removes UMD module ids for rxjs v5 as they conflict with rxjs v6. By default, ng-packagr now suppors rxjs v6.
BREAKING CHANGE: UMD module ids for rxjs v5 are now longer provided out-ot-the-box. Users whishing to a build library for `rxjs@5` (potentially relying on `rxjs-compat`), must provide the UMD module IDs in the `ngPackage.lib.umdModuleIds` section. Please take a look at the changeset of PR #840 to see what the UMD module IDs used to be for v5.
Closes #781, Closes #838
```
[x] Yes
[ ] No
```

feat: provide `UMD module` id defaults for `RXJS` v6

---

.vscode/launch.json
integration/samples/issue-852/bar/package.json
integration/samples/issue-852/bar/public-api.ts
integration/samples/issue-852/foo/package.json
integration/samples/issue-852/foo/public-api.ts
integration/samples/issue-852/package.json
integration/samples/issue-852/public-api.ts
integration/samples/issue-852/some-component/package.json
integration/samples/issue-852/some-component/public-api.ts
integration/samples/issue-852/spec/metadata.ts
src/lib/ng-v5/entry-point/ts/compile-ngc.transform.ts
src/lib/ng-v5/init/init-tsconfig.transform.ts
src/lib/ts/tsconfig.ts

```
[x] Bug Fix
[ ] Feature
```
Config paths needs to be added for all entry points and are also required when analysing.
This change  makes sure that also transitive dependencies, like `a -> b -> c`, the path of `c` is configured when building `a`.
Closes #852
```
[ ] Yes
[x] No
```

fix: auto-wire paths for transitive dependencies of entry points

---

integration/consumers/ng-cli/package-lock.json
src/lib/ng-v5/init/analyse-sources.transform.ts

```
[x] Bug Fix
[ ] Feature
```
At the moment, when a library depends on itself, it fails silently without any error.
Closes: #855
```
[ ] Yes
[x] No
```

fix: throw an error when a circular dependency is detected

---

src/lib/flatten/external-module-id-strategy.ts

```
[ ] Bug Fix
[ ] Feature
```
this is following comment 
https://github.com/dherges/ng-packagr/pull/868#discussion_r187790064
```
[ ] Yes
[x] No
```

refactor: clean up `ExternalModuleIdStrategy`

---

README.md

The default location for `public_api.ts` in a sub-package is within the `package-name/src` dir not in the root of the sub-package.
```
[ ] Bug Fix
[ ] Feature
fix docs
```
```
[ ] Yes
[x] No
```

fix sub-packages docs default public_api location

---

src/lib/ng-v5/discover-packages.ts

```
[ ] Bug Fix
[ ] Feature
```
`node_modules` were still being scanned as the folder was not being ignored.
Closes: #921
```
[ ] Yes
[x] No
```

perf: speed up discovery of secondary entry points

---

src/lib/ng-v5/discover-packages.ts
src/lib/ng-v5/entry-point/write-package.transform.ts

```
[x] Bug Fix
[ ] Feature
```
Change ignore glob from `**/node_modules/**/*` to `**/node_modules/**` the last will improve performance as it won't scan the complete tree.
Closes: #948
//cc @CarstenLeue

perf: don't scan `node_modules` directory while globbing

---

src/lib/ng-v5/discover-packages.ts
src/lib/ng-v5/entry-point/write-package.transform.ts

```
[x] Bug Fix
[ ] Feature
```
Change ignore glob from `**/node_modules/**/*` to `**/node_modules/**` the last will improve performance as it won't scan the complete tree.
Closes: #948

perf: don't scan `node_modules` directory while globbing (V3)

---

src/lib/ng-v5/entry-point/ts/compile-ngc.transform.ts

```
[x] Bug Fix
[ ] Feature
```
We have a memory leak because memory allocs of the TypeScirpt compiler are not released. The effect becomes worse with the number of secondary entry points, as memory allocations were kept for each entry point.
The change disposes the TypeScript transformation result and releases it from the build graph.
```
[ ] Yes
[x] No
```

fix: release typescript compiler memory allocations

---

.appveyor.yml
integration/consumers.sh
integration/samples.sh
integration/samples/core/specs/es2015-api.ts

Samples - the following error was being emitted `FIND: Parameter format not correct`, this is due that `find` is different in Unix and Windows system.
Consumers - fix `fatal error - cygheap base mismatch detected`
Closes: #962

ci: fixes error on windows ci

---

src/lib/file/file-watcher.ts
src/lib/ng-v5/package.transform.ts

```
[x] Bug Fix
[ ] Feature
```
In some cases on windows the same event is emitted twice. Instead of throttle we should debounce. Also, the same think happens when a folder is renamed, While we do have a swictchMap it's still better to trigger it once, in order not to end up with an invalid state,
```
[ ] Yes
[x] No
```

fix: debounce when a file changes

---

docs/override-tsconfig.md

```
[ ] Bug Fix
[ ] Feature
[X] Other: Documentation
```
- [NA] Tests for the changes have been added
I ran into an issue with my ambient types because `@types/sinon` includes [conditional types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#conditional-types) which are a `TypeScript@2.8` feature. My `tsconfig.json` exclude `sinon` ambient types but this is not the case in internal `tsconfig.ngc.json`. I found the docs on overriding tsconfig and I wanted to share the `extends` solution.
```
[ ] Yes
[X] No
```

docs: tsconfig.ngc.json extension

---

src/lib/file/file-watcher.ts

When the observable has complete or errored. The watch should be closed.
```
[ ] Bug Fix
[ ] Feature
```
apply tier down logic so that when observable completes we close the watcher and thus avoid memory leaks
```
[ ] Yes
[ ] No
```

perf: add teardown logic for watch

---

.gitignore
integration/tsconfig.specs.json
integration/watch/basic.spec.ts
integration/watch/basic/package.json
integration/watch/basic/public_api.ts
integration/watch/basic/src/primary.component.ts
integration/watch/basic/src/primary.module.ts
integration/watch/basic/test_files/invalid-type/public_api.ts
integration/watch/basic/test_files/valid-text/public_api.ts
integration/watch/test-harness.ts
package.json
src/lib/ng-v5/package.transform.ts
src/lib/ng-v5/packagr.ts

```
[ ] Bug Fix
[x] Feature
```
1) add a testing harness for incremental builds together with some basic tests cases
2) At the moment, when doing having `watch`, the `build` promise will never get resolved due to that the observable never completes. Exposing an observable sequence makes it also easier for consumers to `close` the `watch` and do more when an observable pipeline.
```
[ ] Yes
[x] No
```
Part of: https://github.com/dherges/ng-packagr/issues/974

testing incremental builds & emit observable

---

integration/tsconfig.specs.json
src/lib/file/file-cache.spec.ts
src/lib/file/file-cache.ts
src/lib/file/file-watcher.ts
src/lib/ng-v5/package.transform.ts
src/tsconfig.packagr.json
src/tsconfig.specs.json
tsconfig.json

We don't need to trigger on directory removed or renamed as chokidar will fire the changes for each file

refactor: remove custom delete strategy for filecache

---

src/lib/file/file-watcher.ts

```
[ ] Bug Fix
[x] Feature
```
In some cases consumers which have a seperate watch running that will update `node_modules` due to an `npm link`. We shall not exclude `node_modules` from being watched for this usecase.
```
[ ] Yes
[x] No
```

fix: don't exclude `node_modules` from watch

---

integration/watch/basic.spec.ts
integration/watch/intra-dependent.spec.ts
integration/watch/intra-dependent/package.json
integration/watch/intra-dependent/public_api.ts
integration/watch/intra-dependent/secondary/package.json
integration/watch/intra-dependent/secondary/public_api.ts
integration/watch/intra-dependent/secondary/src/secondary.component.ts
integration/watch/intra-dependent/secondary/src/secondary.module.ts
integration/watch/intra-dependent/src/primary.component.ts
integration/watch/intra-dependent/src/primary.module.ts
integration/watch/intra-dependent/src/primary.service.ts
integration/watch/intra-dependent/test_files/invalid-component-property/src/primary.component.ts
integration/watch/intra-dependent/test_files/invalid-service-method/src/primary.service.ts
integration/watch/intra-dependent/test_files/valid/src/primary.component.ts
integration/watch/intra-dependent/test_files/valid/src/primary.service.ts
integration/watch/intra-dependent/third/package.json
integration/watch/intra-dependent/third/public_api.ts
integration/watch/intra-dependent/third/src/third.component.ts
integration/watch/intra-dependent/third/src/third.module.ts
integration/watch/test-harness.ts
package.json
src/lib/file/file-cache.ts
src/lib/ng-v5/package.transform.ts
src/lib/ts/cache-compiler-host.ts

When the public API that is consumed from another entrypoint changes, the updated API changes are now reflected in the secondary entrypoint. Also, now only entrypoints that are effected by this file change will be marked as `dirty` and therefore scheduled to be built.
Relates: #974

feat: build only entrypoints that are effected by the changed

---

integration/samples/typings/specs/typings.ts
integration/samples/typings/src/nested/reference/index.ts
integration/samples/typings/src/nested/reference/mocked.d.ts
integration/samples/typings/src/public_api.ts
src/lib/ng-v5/entry-point/write-package.transform.ts

```
[x] Bug Fix
[ ] Feature
```
- [] Tests for the changes have been added
At the moment, typings reference with the triple slash reference are copied to the root dist path, and is causing the folder structure to be lost.
Closes: #1007
```
[ ] Yes
[x] No
```

fix: copy nested triple slash referenced typings to correct path (v4)

---

integration/samples/typings/specs/typings.ts
integration/samples/typings/src/nested/reference/index.ts
integration/samples/typings/src/nested/reference/mocked.d.ts
integration/samples/typings/src/public_api.ts
src/lib/ng-v5/entry-point/write-package.transform.ts

Backporting https://github.com/dherges/ng-packagr/pull/1009 to v3

fix: copy nested triple slash referenced typings to correct path (v3)

---

src/lib/ts/tsconfig.ts

Having this off might break a lot of users that are using Angular-CLI as they might skip reading the changelog and the resulting error message is a bit ambiguous.
Closes #976
//cc @filipesilva

fix: add `enableResourceInlining` by default

---

src/lib/ng-v5/init/analyse-sources.transform.ts

```
[ ] Bug Fix
[ ] Feature
```
At the moment, on incremental builds this is being done for all entrypoints even once that are not marked dirty.
```
[ ] Yes
[x] No
```

perf: analyse sources only for dirty entrypoints

---

integration/samples/core/specs/sourcemaps.ts
src/lib/flatten/rollup.ts

```
[x] Bug Fix
[ ] Feature
```
In some cases when a `null` is returned this will cause webpack loader to fail as there are no null checks.
```
[ ] Yes
[x] No
```
//cc @stephenlautier

fix: add fallback for `sources` when re-wiring sourcemaps

---

src/lib/ts/tsconfig.ts

Concat doesnt mutate the array but rather return a new instance which at the moment is not being used.

fix: tsconfig path mapping

---

src/lib/ng-v5/entry-point/ts/compile-ngc.transform.ts
src/lib/ng-v5/init/analyse-sources.transform.ts
src/lib/ng-v5/nodes.ts
src/lib/ng-v5/package.transform.ts
src/lib/ngc/compile-source-files.ts
src/lib/ts/cache-compiler-host.ts

Previously we had a source file cache for each entrypoint, with this change we unify it to have a single one for all the entrypoints, so that when having a lot of entrypoints we don't cache node_modules and files more than once.
Closes #1099

fix: `JavaScript heap out of memory` when having a lot of secondary entrypoints

---

src/lib/brocc/node.ts

This call is heavy when having a lot of nodes. It has multiple concats and filters and can cause perf issues when having a lot of nodes

perf: reduce the calls to dependsOn

---

integration/samples/core/specs/es2015-api.ts
integration/samples/core/specs/es5-api.ts
package.json
src/lib/ngc/create-emit-callback.ts
src/lib/ts/conf/tsconfig.ngc.json

Fix #1202
```
[ ] Bug Fix
[ ] Feature
```
BREAKING CHANGE: Users outside of Google don't usually need closure annotations hence `annotateForClosureCompiler` is turned off by default. In case users want to emit closure compatable code. they need to install `tsickle` and enable opt it this feature.
```
[x] Yes
[ ] No
```

feat: remove tsickle from direct peerDepedencies

---

integration/samples/material/baz/baz.component.scss
integration/samples/material/specs/metadata.ts
integration/samples/package-json/baz/baz.component.scss
integration/samples/scss-paths/baz/baz.component.sass
integration/samples/scss-paths/baz/baz.component.scss
integration/samples/secondary/primary/baz/baz.component.scss
package.json
src/lib/ng-v5/entry-point/resources/stylesheet-processor.ts
yarn.lock

```
[ ] Bug Fix
[x] Feature
```
Fixes Issue : https://github.com/ng-packagr/ng-packagr/issues/1236
As this is a core angular CLI package, we should follow suit with how the sass compiler works. As of angular CLI  8, dart-sass will be the default dependency with node-sass being supported (https://github.com/angular/angular-cli/pull/13950).
If you wish to use `node-sass` instead of `sass` you need to install node-sass as a dev dependency.
npm users:
`npm install node-sass --save-dev`
yarn users
`yarn add node-sass --dev`
```
[x] Yes
[ ] No
```
Moving to dart-sass as the default compiler _might_ causes a few people issue because of the few decencies between dart-sass and node-sass. For information of the differences, please refer to …

Optional node sass

---

src/lib/ng-v5/discover-packages.ts

fix: error out gracefully when `package.json` is not found

---

src/lib/ngc/compile-source-files.ts

In some cases, when a direct dependency is not build we are not emitting an error and rollup would would because the entrypoint cannot be resolved.
Closes https://github.com/angular/angular-cli/issues/14164

fix: emit ts option diagnostic

---

src/lib/ng-v5/entry-point/write-package.transform.ts

```
[ ] Bug Fix
[ ] Feature
```
Removes the messages related to the scripts section of `package.json` when that section does not exist. The `Removing scripts section in package.json as it's considered a potential security vulnerability.` message should not exist when there is no scripts section to cause a **potential security vulnerability**.
```
... 
Building Angular Package
Building entry point '@scope/packages/subpackage1'
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Copying declaration files
Writing package metadata
Removing scripts section in package.json as it's …
```

build: remove irrelevant scripts section removal warning

---

.appveyor.yml

In windows ci these tests always fail however locally on a windows machine they pass
Re-enable when fixed
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

ci: disable watch tests in windows as they always fail

---

src/lib/ng-v5/entry-point/resources/stylesheet-processor.ts

Use `require.resolve` to always resolve to the correct less binary
Fixes #1276

fix: fix resolution for less binary

---

README.md

```
[ ] Bug Fix
[ ] Feature
```
Removes the sponsoring links that are now outdated due to https://github.com/ng-packagr/ng-packagr/pull/1296
```
[ ] Yes
[x] No
```

fix: remove deprecated sponsoring badges

---

src/lib/ng-v5/entry-point/resources/stylesheet-processor.ts

```
[x] Bug Fix
[ ] Feature
```
Added quote marks to the include-path parameter when bundling `.less` files.
Without this, having whitespace characters in the path of any file specified by the `styleIncludePaths` configuration breaks the packaging process.
```
[ ] Yes
[x] No
```

fix: add quotes to less include-path

---

package.json
src/lib/ng-package-format/entry-point.ts
src/lib/ng-v5/discover-packages.ts
src/ng-package.schema.json
yarn.lock

Remove deprecate `@ngtools/json-schema` in favour of ajv

feat: use `ajv` to validate schema

---

integration/samples/apf/specs/package.ts
integration/samples/ivy/specs/package.ts
src/lib/ng-v5/entry-point/write-package.transform.ts

Publishing of Ivy packages should not be allowed, as there Ivy packages are not backward compatible with VE applications.
With this change we use the npm/yarn prepublishOnly hook to display and error and abort the process with a non zero error code when a user tries to publish an Ivy version of the package.
More info: https://docs.npmjs.com/misc/scripts

feat: show error when trying to publish ivy packages

---

integration/samples/api/tsconfig.ngc.json
src/lib/ngc/compile-source-files.ts
src/lib/ts/conf/tsconfig.ngc.json
src/lib/ts/ctor-parameters.ts

With this change tsickle is no longer needed to be enabled by default. Previously it was needed to TDZ that was caused by forwardRef.
Closes: #1400

fix: add downlevelConstructorParameters transformer

---

docs/secondary-entrypoints.md
integration/samples/secondary/feature-d/feature-d.ts
integration/samples/secondary/feature-d/ng-package.json
integration/samples/secondary/specs/ep-feature-d.ts
src/lib/ng-v5/discover-packages.ts

Currently secondary entry points are breaking `no-implicit-dependencies` TSLint rule, because the
rule is checking for package.json files, which in secondary entry points are anyway just containing
`ngPackage` configuration. Adding the support for ng-package.json removes the need for package.json,
thus TSLint will look correctly in parent package.json file and act accordingly.
fix 1391
```
[x] Bug Fix
[ ] Feature
```
Fixes: [1391](https://github.com/ng-packagr/ng-packagr/issues/1391)
```
[ ] Yes
[x] No
```

fix: support the ng-package.json in secondary entry points

---

integration/consumers/ng-cli/package.json
integration/consumers/ng-cli/yarn.lock
integration/samples/ctor-decorator/README.md
integration/samples/ctor-decorator/ng-package.json
integration/samples/ctor-decorator/package.json
integration/samples/ctor-decorator/public_api.ts
integration/samples/ctor-decorator/specs/es2015-api.ts
integration/samples/ctor-decorator/src/angular.component.ts
integration/samples/ctor-decorator/src/angular.module.ts
src/lib/ngc/create-emit-callback.ts
src/lib/ts/tsconfig.ts

t the moment, we are always setting `emitDecoratorMetadata`, this causes a problem in ES2015 when using `forwardRef`.
With https://github.com/ng-packagr/ng-packagr/pull/1401 `emitDecoratorMetadata` is no longer needed unless using `tsickle`.
`createEmitCallback` has been updated for this reason and also their is a PR for compiler-cli to do the same https://github.com/angular/angular/pull/32880

fix: disable internal `emitDecoratorMetadata`

---

src/lib/ngc/ngcc-processor.ts

Re prioritize ngcc based on the CLI mainFields https://github.com/angular/angular-cli/blob/0d70565f9d80f1d765622eb8c8b2c3c701723599/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts#L68

fix: re prioritize ngcc `propertiesToConsider` properties based

---

src/lib/ng-v5/entry-point/write-bundles.transform.ts

List the depedency in the "peerDependencies" section instead.

feat: deprecate inlining of `bundledDependencies`

---

package.json

TypeScript versions prior to 3.6.4 are no longer supported.no longer supported.

feat: add support to TypeScript 3.6

---

README.md
integration/samples/scss-paths/baz/baz component.less
package.json
src/lib/ng-v5/entry-point/resources/stylesheet-processor.ts
yarn.lock

BREAKING CHANGE: 
Remove usage of deprecated `less-plugin-npm-import`. In less v3 is supports node_modules resolutions by default.
Before
```css
@import '~module/less/linenumbers';
```
After
```css
@import 'module/less/linenumbers';
```

refactor: remove less-plugin-npm-import

---

package.json
yarn.lock

Rollup 1.26.0 introduced a regression see: https://github.com/rollup/rollup/issues/3196
Closes #1431
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix: lock rollup version

---

src/lib/ts/tsconfig.ts

```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

refactor: deprecate `languageLevel` and `jsx` options

---

src/lib/ngc/create-emit-callback.ts

Otherwise they get a `/**` block comment with `@fileoverview added by tsickle`
prepended to them and rollup cannot `JSON.parse()` the file contents.
Fixes #325
```
[x] Bug Fix
[ ] Feature
```
Ignore JSON files in tsickle processing so rollup won't fail when calling `JSON.parse()` on the file contents.
Fixes #325
```
[ ] Yes
[x] No
```
WIP: I will edit the commit message to apply to the Conventional Commits syntax, and I will create a test. (I started this change from the GitHub editor.)

Ignore JSON files in tsickle processing

---

src/lib/ng-package/entry-point/init-tsconfig.transform.ts

```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix: replace ivy warning link to point to v9 instead of next

---

src/lib/ngc/compile-source-files.ts

Only run `downlevelConstructorParameters` when `annotateForClosureCompiler` is not enabled since tsickle will downlevel the ctor params anyways.
Closes #1517

fix:  downlevel constructor parameters transformer with tsickle

---

src/lib/ts/ctor-parameters.ts

Currently constructor parameters with union types that contains nullable argument are not being converted properly and result in broken behaviour.
With this change we align the ctor-parameters downlevel transformer to be closer to the NGTSC reflector: https://github.com/angular/angular/blob/master/packages/compiler-cli/src/ngtsc/reflection/src/typescript.ts#L65-L66
More info: https://github.com/angular/angular-cli/pull/17077

fix: handle union type with a nullable argument

---

integration/samples/apf/specs/package.ts
src/lib/ng-package/entry-point/write-package.transform.ts

Tslib version is bound to the TypeScript version used to comopile the library. Thus, we shouldn't list`tslib` as a  `peerDependencies`. This is because, a user can install libraries which have been compiled with older versions of TypeScript and thus require multiple `tslib` versions to be installed.
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix: auto add tslib as direct dependency

---

integration/samples/custom/ng-package.json
src/ng-package.schema.json

`cssUrl` option default value has been changed to `inline`
More info about this option can be found: https://github.com/ng-packagr/ng-packagr/blob/master/docs/embed-assets-css.md

feat: embed assets in css file using data uri by default

---

integration/samples/core/specs/sourcemaps.ts
src/lib/flatten/rollup.ts
src/lib/ts/tsconfig.ts

fix: remove custom namespaced sourceRoot in sourcemaps

---

src/lib/ng-package/entry-point/write-package.transform.ts

fix: watch assets files and re-copy on changes

---

src/lib/ng-package/entry-point/compile-ngc.transform.ts
src/lib/ngc/ngcc-processor.ts

The NgccProcessor now passes the tsconfig path to ngcc
rather than the `paths` property, since ngcc is able to read
the paths from the tsconfig directly.
See https://github.com/angular/angular/issues/36386#issuecomment-658943132

fix: pass tsconfig path to ngcc

---

src/lib/flatten/rollup.ts
src/lib/ng-package/entry-point/write-bundles.transform.ts
src/lib/ng-package/nodes.ts

With this change we cache rollup AST and plugin cache between incremental runs
Closes #1580

perf: implement rollup caching

---

src/lib/ng-package/discover-packages.ts
src/lib/ng-package/entry-point/entry-point.ts

```
[ ] Bug Fix
[ ] Feature
```
The `secondaryEntryPoint()` receives the basePath information twice: once as a parameter and once as information on the primary entry point, I removed the parameter.
I've also went ahead and updated the `UserPackage` interface to have stricter types and added an extra check for the `package.json` configuration.
```
[ ] Yes
[x] No
```

chore: remove redundant param

---

src/lib/ng-package/entry-point/entry-point.spec.ts

```
[ ] Bug Fix
[ ] Feature
```
Added tests for NgEntryPoint public properties, I'm planing to cleanup this area and later add some improvements for a couple of existing issues, and this way, I make sure that things won't break.
```
[ ] Yes
[x] No
```

test: add tests for primary and secondary entry points

---

integration/samples/apf/specs/package.ts

```
[ ] Bug Fix
[ ] Feature
```
Added `package.json` value tests to cover all entry points for `integration/samples/apf`, including `@sample/apf/secondary/testing`.
```
[ ] Yes
[x] No
```

test: add tests for all APF secondary entry points

---

src/lib/graph/build-graph.ts
src/lib/ng-package/entry-point/analyse-sources.transform.ts
src/lib/ng-package/entry-point/compile-ngc.transform.ts
src/lib/ng-package/entry-point/init-tsconfig.transform.ts
src/lib/ng-package/entry-point/write-bundles.transform.ts
src/lib/ng-package/entry-point/write-package.transform.ts
src/lib/ng-package/nodes.ts
src/lib/ng-package/package.transform.ts
src/lib/ngc/compile-source-files.ts

```
[ ] Bug Fix
[ ] Feature
```
Improves type safety for the BuildGraph.
Besides the type changes, only one extra type guard was added, but it should have no effect at runtime:
```
const foundNode = graph.get(pkgUri);
if (!isPackage(foundNode)) {
return graph;
}
const ngPkg: PackageNode = foundNode;
```
```
[ ] Yes
[x] No
```

refactor: use TypeScript generics for the Traversable BuildGraph

---

integration/watch/intra-dependent.spec.ts
integration/watch/intra-dependent/test_files/circular/src/primary.service.ts
src/lib/ng-package/discover-packages.ts
src/lib/ng-package/entry-point/compile-ngc.transform.ts
src/lib/ng-package/ngcc-cache.ts
src/lib/ng-package/nodes.ts
src/lib/ng-package/package.transform.ts
src/lib/ng-package/schema.ts
src/lib/ngc/ngcc-processor.ts

Performance optimizations

---

src/lib/ts/tsconfig.ts

When setting `sourceRoot` the inlined sourcemap will differ based on the physical location of the library when built.
Closes https://github.com/angular/angular-cli/issues/19335

fix: sourcemap should not differ based on build path

---

src/lib/ng-package/entry-point/compile-ngc.transform.ts
src/lib/ng-package/entry-point/write-package.transform.ts
src/lib/ngc/ngcc-processor.ts

With this change we run the async version of NGCC prior to module resolution.
Fixes: https://github.com/angular/angular-cli/issues/19817

feat: add NGCC async integration

---

src/lib/ng-package/entry-point/compile-ngc.di.ts
src/lib/ng-package/entry-point/compile-ngc.transform.ts
src/lib/ng-package/entry-point/entry-point.di.ts
src/lib/styles/stylesheet-processor.di.ts

```
[ ] Bug Fix
[x] Feature
```
Add a feature customizing `StylesheetProcessor` through dependency injection.
Future usage example:
```ts
export class MyStylesheetProcessor extends StylesheetProcessor {
process(filePath: string, content: string) {
// pre compile scripts
console.debug('content:', content);
return super.process(filePath, content);
}
}
const packager = ngPackagr();
packager.withProviders([{
provide: STYLESHEET_PROCESSOR_TOKEN,
useFactory: () => MyStylesheetProcessor,
deps: [],
}]);
```
This will enable users to transform stylesheets before compiled. 
I can get a lot of flexibility about compiling stylesheets.
```
[ ] Yes
[x] No …
```

feat: enable customizing Stylesheet Processor through dependency injection

---

integration/samples.sh

```
[x] Bug Fix
[ ] Feature
```
Makes the shell code compatible with more systems by using POSIX compatible code. Main changes:
* Disabled glob expansion in favor of a simple dir command, this fixed a bug where the find command was actually treated as a glob and not as an actual command.
* Toggling the fail on error flag to avoid using `|| true`, this fixed a bug where builds that were expected to fail could stop failing because of regressions in the build system and the script would not see this as a problem.
* Took the liberty and added a link to ShellCheck, which is a nice utility that's available on most system.
```
[ ] Yes
[x] No
```

test: use POSIX compatible code for building integration samples

---

package.json
yarn.lock

```
[ ] Bug Fix
[ ] Feature
```
`uglify-js` has been replaced by `@types/uglify-js in a18d7ad2, this PR removes the types which are no longer used.
```
[ ] Yes
[x] No
```

build: remove @types/uglify-js from devDependencies

---

package.json
src/cli/main.ts
src/lib/commands/version.command.ts
yarn.lock

```
[ ] Bug Fix
[ ] Feature
```
Removed direct dependency on `read-pkg-up@5`, it adds 40 dependencies for users of `ng-packagr`, and this dependency can be replaced by a few lines of code.
NOTE: The project still has an indirect dev-dependency through `standard-version`, which is used for making releases.
```
[ ] Yes
[x] No
```
--- 
Closes #1407

refactor: remove read-pkg-up dependency

---

package.json
src/lib/utils/color.ts
src/lib/utils/fs.ts

Node.js version 10 will become EOL on 2021-04-30.
Angular CLI 12 will require Node.js 12.13+ or 14.15+. Node.js 12.13 and 14.15 are the first LTS releases for their respective majors.

refactor: update to use Node 12 APIs

---

package.json
src/lib/styles/stylesheet-processor-worker.ts
src/lib/styles/stylesheet-processor.ts
yarn.lock

By using sync-rpc ( which is also used by the [babel-plugin-postcss](https://github.com/unlight/babel-plugin-postcss/blob/master/src/getcss.ts#L14-L15) package ), we increase the performance
over execFileSync calls, which are very expensive.
```
[x] Performance improvement
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[x] No
```

perf: use sync-rcp instead of execFileSync to transform async function to sync functions #1872

---

src/lib/ts/cache-compiler-host.ts

Closes https://github.com/angular/angular-cli/issues/20080

fix: show error when template file is unreadable

---

docs/dependencies.md
integration/samples/externals/ng-package.json
src/lib/ng-package/entry-point/write-package.transform.ts
src/lib/ng-package/package.ts
src/ng-package.schema.json

```
[ ] Bug Fix
[ ] Feature
```
https://github.com/ng-packagr/ng-packagr/issues/1884
Moved the functionality of `whitelistedNonPeerDependencies` into `allowedNonPeerDependencies`. 
Updated the JSON schema to reflect that `whitelistedNonPeerDependencies` is a deprecated field, added `allowedNonPeerDependencies` to the schema.  Also updated the documentation where the phrasing "white list" appears.
Added a warning message if `whitelistedNonPeerDependencies` is detected in the ng-package.json that it is being deprecated.
```
[ ] Yes
[X] No
```

refactor: renaming whitelistedNonPeerDependencies in favor of allowedNonPeerDependencies

---

src/lib/ng-package/entry-point/init-tsconfig.transform.ts
src/lib/ng-package/entry-point/write-package.transform.ts

Ivy libraries are not allowed to be published when compiled in partial mode. To enable this mode, add `compilationMode: "partial"` under the `angularCompilerOptions` section in the library's tsconfig.
Closes #1901

feat: allow publishing of Ivy library in partial mode.

---

src/lib/styles/stylesheet-processor-worker.ts

CSS declaration orders matters in some cases. This optimization is currently causing broken CSS output.

fix: disable CSS declaration sorting optimizations

---

integration/watch/basic.spec.ts
integration/watch/test-harness.ts
src/lib/ng-package/entry-point/write-package.di.ts
src/lib/ng-package/entry-point/write-package.transform.ts

During watch builds we add a stamped version in the `package.json`, so that it can be used to invalidate Webpack's build cache.
Closes https://github.com/angular/angular-cli/issues/20962

fix: add version stamping during watch builds

---

src/lib/ivy/compile-source-files.ts

The AOT compiler's internal template type-checking files are not intended to be directly analyzed for diagnostics by the emitting program and are instead analyzed during the template type-checking phase. Previously, only semantic diagnostics were ignored. Now both syntactic and semantic diagnostics are ignored. This change prevents non-actionable diagnostics from being shown during a build.
Addresses: angular/angular#42667
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] …
```

fix avoid non-actionable template type-checker syntax diagnostics

---

integration/samples/scss-paths/specs/metadata.ts
package.json
src/lib/ivy/styles/stylesheet-processor.ts
src/lib/styles/stylesheet-processor-worker.ts
yarn.lock

The stylesheet optimization pipeline now uses esbuild for component stylesheets. The usage of esbuild provides noticeable build time improvements as well as, on average, smaller output sizes.

perf: use esbuild as a CSS optimizer for component styles

---

integration/samples/inline-style-language/ng-package.json
integration/samples/inline-style-language/package.json
integration/samples/inline-style-language/public_api.ts
integration/samples/inline-style-language/specs/build.ts
integration/samples/inline-style-language/src/angular.component.ts
integration/samples/inline-style-language/src/angular.module.ts
package.json
src/lib/ng-package/entry-point/analyse-sources.transform.ts
src/lib/ng-package/package.ts
src/lib/ngc/compile-source-files.ts
src/lib/styles/stylesheet-processor.ts
src/lib/ts/cache-compiler-host.ts
src/ng-package.schema.json
yarn.lock

A new  option named `inlineStyleLanguage` has been introduced that will allow a project to define the stylesheet language used in a library's inline component styles

feat: support specifying stylesheet language for inline component styles

---

src/lib/styles/stylesheet-processor.ts

BREAKING CHANGE: Support for `node-sass`  has been removed. sass will be used by default to compile SASS and SCSS files.

feat: drop support for node-sass

---

docs/dependencies.md

The UMD bundles have been removed in APF13 so this commit the UMD module name configuration from the documentation.

docs: remove section on UMD module names

---

src/lib/utils/color.ts

```
[x] Bug Fix
[ ] Feature
```
In some cases, custom implementation of stdout, don't extend `WriteStream` which causes colors not to be included in the output.
This pull request is the same that @alan-agius4  made in @angular/cli [here](https://github.com/angular/angular-cli/commit/d3fa202e9a26926f0660b1e1f156012ea41b1711)  
@alan-agius4  has all the merits, thank you
```
[ ] Yes
[x] No
```

fix:handle FORCE_COLOR when stdout is not instance of 'WriteStream'

---

src/lib/flatten/rollup.ts

```
[x] Bug Fix
```
The rollup bundle must be closed once `write` is finished to let plugins clean up their external processes or services via the `closeBundle` hook, otherwise it can lead to memory leaks.
```
[x] No
```

fix: close rollup bundle after write

---

src/lib/ts/tsconfig.ts

Closes #2228
```
[x] Bug Fix
[ ] Feature
```
Replacing a 404 ivy link with a pair of non 404 files pinned to angular 12 in the angular repository that relate to ivy.
```
[ ] Yes
[x] No
```

fix: link to angular 12 ivy docs

---

src/lib/styles/stylesheet-processor.ts

This issue address the Invalid version: `"15.2-15.3"` range. We previously only handled version ranges for `ios_safari`. Now, we handle such versions for all browsers.
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix: invalid browsers version ranges

---

src/lib/ng-package/entry-point/write-package.transform.ts

```
[ ] Bug Fix
[ ] Feature
```
Fixes formatting in the peerDependency warning
```
[ ] Yes
[x] No
```

style: fix formatting in peerDependency warning

---

package.json
src/lib/utils/fs.ts

Node.js v12 will become EOL on 2022-04-30. As a result, Angular CLI v14 will no longer support Node.js v12.
Support for Node.js v12 has been removed as it will become EOL on 2022-04-30. Please use Node.js v14.15 or later.

feat: drop support for Node.js 12

---

package.json
yarn.lock

Support for TypeScript 4.4 and 4.5 has been removed. Please update to TypeScript 4.6.

feat: support TypeScript 4.6.2

---

src/lib/graph/build-graph.ts
src/lib/styles/stylesheet-processor.ts

```
[ ] Bug Fix
[ ] Feature
```
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
```
[ ] Yes
[x] No
```

refactor: replace deprecated String.prototype.substr()

---

src/lib/flatten/rollup.ts

```
[ ] Bug Fix
[ ] Feature
```
In [this commit](https://github.com/angular/angular-cli/commit/0a1cd584d8ed00889b177f4284baec7e5427caf2) the `showCircularDependencies` option was removed from the `angular-cli`. This PR makes a corresponding change for `ng-packagr` that suppresses rollout's circular dependency warning during `ng build` as suggested in [this rollout issue](https://github.com/rollup/rollup/issues/2271#issuecomment-475540827).
**Why?**
Circular dependencies often lead to trouble, but sometimes they're a completely valid design tool that both compile and execute just fine. In that case, it doesn't make sense for `ng-packagr` to be …

refactor: suppress rollup circular dependency warnings

---

src/lib/ngc/compile-source-files.ts

Previously, declaration diagnostics were not emitted which caused certain compilation errors not to be emitted.
Closes #2405

fix: emit TypeScript declaration diagnostics

---

src/lib/ng-package/entry-point/analyse-sources.transform.ts

```
[ ] Bug Fix
[ ] Feature
[ x ] Other (Refactoring, Added tests, Documentation, ...)
```
Update wording of error message to use the word **exist** instead of **exists**
_Entry point `${moduleName}` which is required by `${moduleId}` doesn't exist._
See issue #2428
```
[ ] Yes
[ x ] No
```

Grammatical update for error message

---

integration/samples/custom/src/foo-bar/foo-bar.component.styl
integration/samples/custom/src/foo-bar/foo-bar.component.ts
integration/samples/scss-paths/assets/theme.styl
integration/samples/scss-paths/baz/baz.component.styl
integration/samples/scss-paths/baz/baz.component.ts
integration/samples/scss-paths/sub-module/bar/bar.component.styl
integration/samples/scss-paths/sub-module/bar/bar.component.ts
package.json
src/lib/styles/stylesheet-processor.ts
yarn.lock

Deprecated support for Stylus has been removed. The Stylus package has never reached a stable version and it's usage in the ng-packagr is minimal. It's recommended to migrate to another CSS preprocessor that the ng-packagr supports.

refactor: remove support for Stylus

---

integration/samples/material/baz/baz.component.scss
integration/samples/scss-paths/baz/baz.component.sass
integration/samples/scss-paths/baz/baz.component.scss
integration/samples/secondary/primary/baz/baz.component.scss
src/lib/styles/stylesheet-processor.ts

Deprecated support for tilde import has been removed. Please update the imports by removing the `~`.
Before
```scss
@import "~font-awesome/scss/font-awesome";
```
After
```scss
@import "font-awesome/scss/font-awesome";
```

feat: switch to sass modern API

---

package.json

This commit drops support for TypeScript 4.6 and 4.7
BREAKING CHANGE: TypeScript versions older than 4.8.2 are no longer supported.

feat: drop support for TypeScript 4.6 and 4.7

---

integration/samples/tailwindcss/ng-package.json
integration/samples/tailwindcss/package.json
integration/samples/tailwindcss/public_api.ts
integration/samples/tailwindcss/specs/build.ts
integration/samples/tailwindcss/src/angular.component.css
integration/samples/tailwindcss/src/angular.component.ts
integration/samples/tailwindcss/src/angular.module.ts
integration/samples/tailwindcss/tailwind.config.js
package.json
src/lib/ng-package/entry-point/compile-ngc.transform.ts
src/lib/styles/stylesheet-processor.ts
yarn.lock

This feature adds detection of the `tailwindcss` package (https://tailwindcss.com) and provides a mechanism to automatically include support. To enable tailwindcss for a project, two actions must be taken: 1) Install `tailwindcss` (`npm install -D tailwindcss`/`yarn add -D tailwindcss`) 2) Create a tailwindcss configuration file (`tailwind.config.js`) in the project root.  A configuration file in the project root takes precedence over one in the workspace root.
Closes #1943

feat: add support for tailwindcss

---

src/lib/ng-package/entry-point/write-package.transform.ts

fix: exclude scanning nested node_modules when locating `README.md`

---

docs/copy-assets.md

```
[ ] Bug Fix
[ ] Feature
```
There is a new advanced asset copying syntax introduced in the PR #2284. This syntax can be quite helpful for component libraries.
```
[ ] Yes
[x] No
```

docs: mention the new asset copying syntax

---

integration/samples/dynamic-imports/LICENSE
integration/samples/dynamic-imports/README.md
integration/samples/dynamic-imports/ng-package.json
integration/samples/dynamic-imports/package.json
integration/samples/dynamic-imports/public_api.ts
integration/samples/dynamic-imports/specs/files.ts
integration/samples/dynamic-imports/src/primary.component.ts
integration/samples/dynamic-imports/src/primary.module.ts
integration/samples/dynamic-imports/src/sub/lazy-import.ts
src/lib/flatten/rollup.ts
src/lib/ng-package/entry-point/entry-point.ts
src/lib/ng-package/entry-point/write-bundles.transform.ts

This commits add supports to process dynamic imports and output lazy chunks.
**NB:** This does not mean that lazy routing is a good idea to have in a library.  There are cases outside of routing why you might want to use dynamic imports.
Closes https://github.com/angular/angular-cli/issues/21358 and closes https://github.com/ng-packagr/ng-packagr/issues/2508

feat: add support for dynamic import

---

package.json

Updates the peer dependency range to allow for TypeScript 4.9.

build: expand peer dependency version range for typescript

---

package.json
src/lib/ng-package/entry-point/compile-ngc.transform.ts
src/lib/ng-package/package.transform.ts
src/lib/styles/stylesheet-processor-worker.ts
src/lib/styles/stylesheet-processor.ts
src/tsconfig.packagr.json
yarn.lock

Stylesheets will now be processed using a worker pool This allows up to four stylesheets to be processed in parallel and keeps the main thread available for other build tasks.
`NG_BUILD_MAX_WORKERS` environment variable can be used to comfigure the limit of workers used.

perf: move stylesheet processing into a worker pool

---

src/lib/styles/stylesheet-processor-worker.ts

Prior to this change these 2 options where not added as part of the cache key which caused the cache to be invalidated when one of these options change.
Closes #2523

fix: include `cssUrl` and `styleIncludePaths` in the CSS cache key

---

src/lib/styles/stylesheet-processor.ts

angular/angular#48669 added support for the last 2 Chrome versions

fix: update browserslist config to include last 2 Chrome versions

---

src/lib/ng-package/package.ts

The trailing slash causes the watcher to go in an infinite loop.
Closes #2558

fix: remove trailing slash from dest

---

.circleci/config.yml
package.json

BREAKING CHANGE: Node.js v14 support has been removed
Node.js v14 is planned to be End-of-Life on 2023-04-30. Angular will stop supporting Node.js v14 in Angular v16. Angular v16 will continue to officially support Node.js versions v16 and v18.

refactor: remove Node.js v14 support

---

package.json
yarn.lock

Updates the repo to TypeScript 5.0 and drops support for TypeScript 4.8.
* TypeScript 4.8 is no longer supported.

feat: add support for TypeScript 5

---

.circleci/config.yml
package.json

This commit updates the minimum supported Node version across packages from 16.13.0 -> 16.14.0 to ensure compatibility with dependencies.

build: update minimum supported Node version from 16.13.0 -> 16.14.0

---

src/lib/ts/tsconfig.ts

Remove hardcoded `experimentalDecorators` option.
Closes #2625

fix: allow usages of ECMAScript Decorators

---

src/lib/packagr.ts

When using the JS API and `withTsConfig` was not called and error for a missing injector was throw
```
No provider for InjectionToken ng.v5.defaultTsConfig! (InjectionToken ng.v5.packageTransform -> InjectionToken ng.v5.initTsConfigTransform -> InjectionToken ng.v5.defaultTsConfig)
```
Closes https://github.com/angular/angular-cli/issues/25421

fix: no provider for `InjectionToken ng.v5.defaultTsConfig`

---

src/lib/styles/stylesheet-processor-worker.ts

This change aligns the option with that of the Angular CLI as it caused unexpected output.
Closes #2675

fix: do not set less math option

---

src/lib/ng-package/entry-point/analyse-sources.transform.ts
src/lib/ngc/compile-source-files.ts
src/lib/ts/cache-compiler-host.ts

It appears that `builder.emitNextAffectedFile` causes the afterDeclaration transformer not to run which causes the DTS files to be emitted without Angular metadata.
Closes #2664 and closes https://github.com/angular/angular-cli/issues/25706

fix: watch mode not emitted transformed DTS files

---

src/lib/ngc/compile-source-files.ts

Change #2682 caused an incorrect behaviour that caused the tsbuild info not to be emitted.

fix: emit `.tsbuildinfo` when cache mode is enabled

---

package.json

BREAKING CHANGE:  TypeScript versions before 5.2 are no longer supported.

feat: drop support for TypeScript versions before 5.2

---

docs/copy-assets.md

small tweak so the documentation is up to date with ng-packagr schema
```
[ ] Bug Fix
[ ] Feature
[X ] Other (Refactoring, Added tests, Documentation, ...)
```
I found the documentation was reflecting old behavior of ng-packagr in its format for copying assets
```
[ ] Yes
[X ] No
```

fix:Update copy-assets.md to reflect ng-package.json format

---

integration/samples/apf/specs/files.ts
integration/samples/issue-1451/specs/license.ts
integration/samples/keep-output-path/dest/.npmignore
src/lib/ng-package/entry-point/write-package.transform.ts

This commit adds `package.json` in secondary entry-points so that esbuild can resolve secondary entry-points when the library is not in node_modules. Example, when it's being locally build.
Closes: https://github.com/angular/angular-cli/issues/24434

feat: esbuild can't resolve secondary entry point from library

---

src/lib/ngc/compile-source-files.ts

Replace `createAbstractBuilder` with `createEmitAndSemanticDiagnosticsBuilderProgram` to  ensures that template errors are displayed when cache is disabled.
Closes #2705

fix: display template error when cache is disabled

---

package.json
src/lib/styles/stylesheet-processor-worker.ts
yarn.lock

With this change we only use postcss when tailwind is used or an image is needs to be embeeded.
autoprefixer has also been removed in favor of esbuild css vendoring prefixing.

perf: only process component styles with postcss when needed

---

src/lib/commands/version.command.ts
src/lib/flatten/file-loader-plugin.ts
src/lib/ng-package/entry-point/write-bundles.transform.ts
src/lib/ng-package/nodes.ts

Closes: https://github.com/ng-packagr/ng-packagr/issues/2749

fix: remove direct imports to `rollup`

---

src/lib/styles/stylesheet-processor-worker.ts

`@screen` is not documented in tailwind documentation as it is not a recommended option, however it still works and they don't have plans to remove it.
https://github.com/tailwindlabs/tailwindcss/discussions/7516

fix: add missing tailwind `@screen` directive in matcher

---

src/lib/styles/postcss-configuration.ts
src/lib/styles/stylesheet-processor-worker.ts
src/lib/styles/stylesheet-processor.ts

The usage of a custom postcss configuration is now supported.
The builder will automatically detect and use specific postcss configuration files if present in either the project root directory. Files present in the project root will have priority over a workspace root file. If using a custom postcss configuration file, the automatic tailwind integration will be disabled. To use both a custom postcss configuration and tailwind, the tailwind setup must be included in the custom postcss configuration file.
The configuration files must be JSON and named one of the following:
* `postcss.config.json`
* `.postcssrc.json`
A configuration file can use either an array form or an object form to setup plugins.
An example of the array form:
```json
{
"plugins": [
"tailwindcss",
["rtlcss", { "useCalc": …
```

feat: support using custom postcss configuration

---

.circleci/config.yml
.prettierignore
package.json

BREAKING CHANGE: Node.js support for versions <18.19.1 and <20.11.1 has been removed.

refactor: remove support for Node.js versions <18.19.1 and <20.11.1

---

package.json

In angular/angular#54961 the Angular compiler stopped supporting TypeScript versions older than 5.4. These changes narrow down the range for `ng-packagr`.

build: narrow down supported TypeScript versions

---

src/lib/flatten/esbuild.ts

Esbuild will try to locate a tsconfig from the project root when generating FESMs, this sometimes causes incorrect resolutions for secondary entry-points.
Closes #2838

fix: incorrect path resolution for entry-points when generating FESM

---

README.md

```
[ ] Bug Fix
[ ] Feature
```
Update in the README the Angular Package Format links to redirect to the new doc on `angular.dev`.
```
[ ] Yes
[x] No
```

docs: update apf official doc link

---

src/lib/flatten/rollup.ts

This fix disables the rollup option `hoistTransitiveImports` to address issues related to incorrect import behavior.
Closes https://github.com/angular/angular-cli/issues/28221

fix: disable rollups hoistTransitiveImports

---

package.json

Prepares for the updated version range in Angular v19.

build: allow TypeScript 5.6 and drop TypeScript 5.4

---

package.json

Updates the `peerDependencies` to allow Angular `19.1.0-next`.

build: adjust peerDependencies

---

src/lib/ngc/compile-source-files.ts

Replaced `builder.getDeclarationDiagnostics` with `typeScriptProgram.getDeclarationDiagnostics` to avoid performance issues introduced in TypeScript 5.6+ reported in https://github.com/microsoft/TypeScript/issues/60970
Closes #2969

perf: mitigate TypeScript 5.6+ performance regression

---

src/lib/ts/tsconfig.ts

Disabling the `removeComments` option ensures important annotations like `/* @__PURE__ */` are preserved. TypeScript’s comment removal can be overly aggressive and strip out vital information, which is crucial for bundlers to eliminate dead code effectively. Non-essential comments will be handled by the bundler, so there’s no need to remove comments at the TypeScript level. This prevents unnecessary increases in final bundle size.

fix: disable TypeScript `removeComments` option

---

package.json

Narrow down the versions of TypeScript to support.
BREAKING CHANGE: TypeScript versions less than 5.8 are no longer supported.

feat: drop support for TypeScript older than 5.8

---

package.json

BREAKING CHANGE: Node.js versions from 22.0 to 22.10 are no longer supported

fix: update minimum supported Node.js 22 version to 22.11.0

---

src/lib/file-system/file-cache.ts
src/lib/file-system/file-watcher.ts
src/lib/flatten/file-loader-plugin.ts
src/lib/graph/node.ts
src/lib/graph/select.ts
src/lib/ng-package/entry-point/entry-point.ts
src/lib/ng-package/entry-point/write-bundles.transform.ts
src/lib/ng-package/nodes.ts
src/lib/ng-package/package.transform.ts
src/lib/ts/cache-compiler-host.ts

Before this commit, emitting a DTS file would trigger a rebuild of dependent entry points. With this update, a rebuild occurs only if the contents of the DTS file change.
Closes: #2936

perf: prevent redundant entry-point builds in watch mode

---

src/lib/flatten/rollup.ts

Example `WARNING: Generated an empty chunk: "foo.d".` is not not actionable.

fix: disable emitting empty chunk warning

---

src/lib/ts/tsconfig.ts

The Angular compiler does not directly support the `composite` option within a referenced `tsconfig` file. If this option is enabled, the Angular compiler will crash due to the Angular compiler not leveraging the TypeScript BuilderProgram infrastructure. Since the Angular compiler is not aware of composite projects nor project references, the `composite` option is disabled when options are passed to the Angular compiler. This has no effect on non- Angular related usages of the `tsconfig`.

fix: disable TypeScript `composite` option with Angular compiler

---

src/lib/styles/stylesheets/bundle-options.ts

The Angular encapsulation currently does not support CSS nesting syntax, which can lead to run-time errors or unexpected behavior when such styles are used in component stylesheets. This change ensures that nested CSS rules flattened to maintain compatibility with the compiler.
For more context, see: https://github.com/angular/angular/issues/58996

fix: prevent nested CSS in components

---

.browserslistrc
scripts/postbuild.js
src/lib/styles/stylesheet-processor.ts

This changes the default `.browserslistrc` file to one generated from a Baseline "widely available" date using `bl2bl`, codifying the policy change from https://github.com/angular/angular/pull/60754 into `ng-packagr`.
This effectively pins the `.browserslistrc` file to a hard-coded configuration from a specific Baseline date, preventing it from automatically updating based on `caniuse-lite` versions managed in user workspaces, which should make Angular's tooling much more stable. Prior to this, expressions like "last 2 Chrome versions" were relative to the installed `caniuse-lite` version and could update at any time. By pinning `.browserslistrc`, we're ensuring that supported browsers only change during Angular major version updates, not arbitrary `caniuse-lite` updates.
The [Angular CLI …

feat: expand browser support to widely available Baseline
