integration/README.md, integration/consumer-ng-cli/package.json, integration/consumer-ng-cli/src/app/app.module.ts, integration/consumer-ng-cli/yarn.lock, integration/consumer-tsc/consumer.ts, integration/consumer-tsc/tsconfig.json
=> test: integration testing

circle.yml, package.json
Closes #19 
Also, solves #22 by rim-raffing local node_modules
=> ci: automate deployments from circle ci

cli/ng-packagr.js, lib/ng-packagr.ts, lib/util/log.ts
Closes #16 (error reporting) and #35  (fail builds)
=> fix: report Errors with stack traces, fail builds on promise rejection

integration/README.md, integration/consumer-ng-cli/src/app/app.component.html, integration/consumer-ng-cli/src/app/app.module.ts, integration/consumer-tsc/consumer.ts, integration/consumer-tsc/tsconfig.json, lib/ng-packagr.ts, lib/steps/json.ts, lib/steps/tsc.ts, package.json
- fix: adjust filenames for correct source maps 
- test: integration samples reflect current changes
- feat: relocate sources paths in final `*.js.map`
=> fix: correct paths in generated sourcemaps

package.json
=> feat: update rollup to version ^0.45.0

.travis.yml, integration/sample_core/ng-package.json, integration/sample_custom/ng-package.json, integration/sample_material/ng-package.json, lib/model/ng-package.ts, lib/ng-package.schema.json, lib/steps/package.ts, package.json, yarn.lock
=> validate and normalize config values through json schema

integration/samples.js, integration/samples.sh
Refactoring of build scripts (integration testing)
=> Refactor build scripts for integration testing

circle.yml, integration/samples/core/src/angular.service.ts, src/lib/steps/rollup.ts
=> feat: support '@angular/common/http' by default

integration/consumers/ng-cli/package.json, integration/consumers/ng-cli/yarn.lock
=> chore: renovate @angular / lock file maintenance

integration/samples/custom/src/less-baz/less-baz.component.ts, integration/samples/custom/src/public_api.ts, src/lib/steps/assets.ts
```
[x] Bug Fix
[ ] Feature
```
See #165
```
[ ] Yes
[x] No
```
=> test: empty `.less` style file causes build error

package.json
```
[ ] Bug Fix
[ ] Feature
```
Bumped Angular to 4.4.5, refs #101
```
[ ] Yes
[x] No
```
=> Bump angular and ts version

integration/samples/secondary/specs/assets.ts, src/lib/bundler.ts, src/lib/steps/sorcery.ts, src/lib/steps/uglify.ts
```
[ ] Bug Fix
[x] Feature
```
Minify JS bundles to fix #3.
```
[ ] Yes
[x] No - it would only break if uglifyJS fails to minify for some reason
```
=> feat: minify javascript bundles

src/lib/bundler.ts
```
[ ] Bug Fix
[x] Feature
```
Add more frequent console feedback. This should aid in troubleshooting for those who don't know how to get DEBUG output.
```
[ ] Yes
[x] No
```
=> feat: provide more frequent console feedback

src/lib/ng-packagr.ts, src/lib/steps/package.ts
```
[x] Bug Fix
[ ] Feature
```
Resolves #214
```
[ ] Yes
[x] No
```
=> fix: copy `README.md` and `LICENSE` just for primary entry

.travis.yml
```
[ ] Bug Fix
[ ] Feature
```
Travis CI (for pull requests) covers the following node versions:
- latest (9.x)
- 8.x
- 7.x
- 6.x
```
[ ] Yes
[x] No
```
=> ci: run travis ci on node latest (9.x), 8.x, 7.x, and 6x.

src/lib/conf/tsconfig.ngc.json
```
[x] Bug Fix
[ ] Feature
```
Remove explicit type root to fix #177.
Update tsconfig lib to match angular.
```
[ ] Yes
[x] No
```
=>  fix: resolve node_modules folder dynamically from typescript

integration/consumers/ng-cli/package.json, integration/consumers/ng-cli/yarn.lock, integration/samples/custom/src/custom.module.ts, package.json, yarn.lock
```
[ ] Bug Fix
[x] Feature
```
Beginning of migrating to Angular v5
```
[ ] Yes
[x] No
```
=> feat: update typescript to ~2.4.2 for Angular v5 support

package.json, src/lib/steps/ngc.ts, yarn.lock
```
[ ] Bug Fix
[x] Feature
```
Drop `@angular/tsc-wrapped` in favor of `@angular/compiler-cli`. Migrates to v5
Produces aot metadata in version 4.
Fixes #219
```
[ ] Yes
[x] No
```
=> feat: invoke ngc thru `@angular/compiler-cli` version 5.0.x

.circleci/config.yml
```
[ ] Bug Fix
[ ] Feature
```
Configure Circle CI 2.0 Workflows for:
- build any branch except "gh-pages"
- deploy git tags "v1.2.3" to npm registry with tag "latest"
- deploy git tags "v1.2.3-foo.n" to npm registry with tag "foo"
```
[ ] Yes
[x] No
```
=> ci: configure circle ci workflows for npm deployments

CHANGELOG.md
```
[ ] Bug Fix
[ ] Feature
```
Fixes typo in changelog
```
[ ] Yes
[x] No
```
=> just a simple typo fix in changelog

src/lib/steps/ngc.ts
```
[x] Bug Fix
[ ] Feature
```
complier-cil.performCompilation was now silently failing resulting in no compiled code getting written and so when the source mapper ran it got an error because the file it was trying to map didn't exist. Again because performCompilation was silently failing. This checks the result of the compilation to see if it resulted in an error and tries to give the best info it can about this and then throws an exception to stop the whole packaging process.  Notice I had problems getting the typescript namespace (ts) recognized in the ng-packagr build process so  I had to …
=> fix: compiler no longer throwing an error

integration/samples/externals/package.json, integration/samples/externals/public_api.ts, integration/samples/externals/specs/rxjs-lettables.ts, integration/samples/externals/src/rxjs-lettable-operators.ts, package.json, yarn.lock
```
[ ] Bug Fix
[ ] Feature
```
Tests for #307 and the `externals` sample 
```
[ ] Yes
[x] No
```
=> test: integration test for rxjs lettable operators

commitlint.config.js, integration/samples.sh, integration/samples/core/package.json, integration/samples/core/specs/es5-api.ts, integration/samples/core/specs/metadata.ts, integration/samples/core/specs/umd.ts, integration/samples/custom/package.json, integration/samples/custom/specs/es5-api.ts, integration/samples/custom/specs/metadata.ts, integration/samples/jsx/specs/react-jsx.ts, integration/samples/material/specs/assets.ts, integration/samples/material/specs/metadata.ts, integration/samples/secondary/package.json, integration/samples/secondary/specs/es2016-api.ts, integration/samples/secondary/specs/es5-api.ts, integration/tsconfig.specs.json
```
[ ] Bug Fix
[ ] Feature
```
Further improve test coverage.
Verify what are "works as expected" use cases with the current code base. 
```
[ ] Yes
[x] No
```
=> test: enhance quality and coverage of integration testing

src/lib/util/copy.ts
```
[ ] Bug Fix
[x] Feature
```
- [x ] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
```
[ ] Yes
[ ] No
```
=> feat: set coorect type for options in copyFiles

integration/samples/core/specs/sourcemaps.ts, src/lib/bundler.ts, src/lib/steps/sorcery.ts
```
[ ] Bug Fix
[x] Feature
```
A picture tells more than thousand words ... _screenshot wanted
```
[ ] Yes
[x] No
```
=> feat: relocate source map file paths to `ng://<@org>/<package>/<sub>`

package.json
Closes: #341
```
[ ] Bug Fix
[X] Feature
```
Expose API for node usage
```
[ ] Yes
[x] No
```
=> feat: expose node API and typings

.circleci/config.yml
```
[ ] Bug Fix
[ ] Feature
```
Updates Circle CI build for node 8
```
[ ] Yes
[x] No
```
=> ci: run Circle CI build on node 8 (ngcontainer@0.0.5)

src/cli/main.ts, src/lib/version-info.ts
```
[ ] Bug Fix
[x] Feature
```
```bash
$ ng-packagr --version
ng-packagr:            2.0.0-rc.6
@angular/compiler:     5.1.0
@angular/compiler-cli: 5.1.0
rollup:                0.52.1
tsickle:               0.25.5
typescript:            2.5.3
```
```
[ ] Yes
[x] No
```
=> feat: provide version info with `ng-packagr --version` cli option

package.json, scripts/postbuild.js, scripts/prepublish.js
```
[ ] Bug Fix
[ ] Feature
```
The shebang line is not working on Windows
```
[ ] Yes
[x] No
```
=> build: fix scripts on windows

CHANGELOG.md
```
[ ] Bug Fix
[ ] Feature
```
#397 
```
[ ] Yes
[ ] No
```
=> docs: update changelog to clarify on TypeScript dependency versions

src/lib/steps/init.ts
```
[ ] Bug Fix
[ ] Feature
x] Other (Refactoring, Added tests, Documentation, ...)
```
refactor init step
```
[ ] Yes
[x] No
```
=> refactor: `resolvePackageConf` in `init` step

src/lib/entry-point-transforms.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> refactor: remove `umdModuleIds` when using rollup with `es` format

.circleci/config.yml, integration/consumer.sh, integration/consumers/tsc/src/core-consumer/core-consumer.component.ts, integration/consumers/tsc/src/core-consumer/core-consumer.module.ts, integration/consumers/tsc/src/custom-consumer/custom-consumer.component.ts, integration/consumers/tsc/src/custom-consumer/custom-consumer.module.ts, integration/consumers/tsc/src/jsx-consumer/jsx-consumer.component.ts, integration/consumers/tsc/src/jsx-consumer/jsx-consumer.module.ts, integration/consumers/tsc/src/main.ts, integration/consumers/tsc/src/material-consumer/bar-consumer.componene.ts, integration/consumers/tsc/src/material-consumer/baz-consumer.componene.ts, integration/consumers/tsc/src/material-consumer/foo-bar-consumer.componene.ts, integration/consumers/tsc/src/material-consumer/foo-consumer.componene.ts, integration/consumers/tsc/src/material-consumer/material-consumer.module.ts, integration/consumers/tsc/src/module-imports.ts, integration/consumers/tsc/tsconfig.json, integration/samples/core/src/angular.module.ts, integration/samples/core/src/angular.pipe.ts, package.json
```
[ ] Bug Fix
[ ] Feature
```
Enhance coverage of integration tests.
```
[ ] Yes
[x] No
```
=> test: enhance consumer integration tests

.vscode/launch.json, src/lib/domain/build-artefacts.ts, src/lib/entry-point-transforms.ts, src/lib/ng-packagr.ts, src/lib/steps/ngc.ts, src/lib/steps/rollup.ts
```
[ ] Bug Fix
[ ] Feature
```
Tests unchanged.
```
[ ] Yes
[x] No
```
=> refactor: extract `BuildStep` for bundle flattening

package.json
```
[x] Bug Fix
[ ] Feature
```
Closes #452
```
[ ] Yes
[x] No
```
=> fix: update dependendy tsickle to >=0.25.5 <0.26.0

integration/samples/core/specs/es5-api.ts, integration/samples/core/specs/umd.ts, integration/samples/core/src/angular.service.ts, src/lib/steps/tsc.ts
```
[ ] Bug Fix
[x] Feature
```
As discussed in #418
```
[ ] Yes
[x] No
```
=> feat: include downlevelIteration flag for ES5 bundles

.gitignore, integration/samples/material/baz/baz.component.scss, integration/samples/material/specs/metadata.ts, src/lib/steps/assets.ts
Added *.iml to .gitignore
```
[x ] Bug Fix
[ ] Feature
[x ] Other (Refactoring, Added tests, Documentation, ...)
```
- other: extended gitignore
- fix: 
https://github.com/dherges/ng-packagr/issues/425
See: 
https://github.com/dherges/ng-packagr/issues/425
```
[ ] Yes
[ x] No
```
=> Added replace line to escape unicode characters

src/lib/ng-package-format/artefacts.ts, src/lib/ng-v5/packagr.spec.ts, src/lib/ng-v5/packagr.ts, src/lib/steps/build-ng-package.ts, src/lib/steps/entry-point-transforms.ts, src/lib/steps/ngc-tsconfig.ts, src/lib/steps/ngc.ts
```
[ ] Bug Fix
[x] Feature
```
Closes #256 
```
[ ] Yes
[x] No
```
=> feat: enable tsconfig customization thru the programmatic API

README.md
```
[ ] Bug Fix
[ ] Feature
```
Fixes typos in README.md
```
[ ] Yes
[x] No
```
=> [docs] update README.md

src/lib/ts/ng-component-transformer.ts, src/lib/ts/template.visitor.ts, src/lib/ts/transform-component.ts
```
[ ] Bug Fix
[ ] Feature
```
Code re-organization
```
[ ] Yes
[x] No
```
=> refactor: extract `transformComponent` for standalone usage

src/lib/ng-package-format/artefacts.ts, src/lib/steps/ngc.ts, src/lib/ts/synthesized-compiler-host.ts, src/lib/ts/synthesized-source-file.spec.ts, src/lib/ts/synthesized-source-file.ts, src/lib/ts/template.visitor.ts
```
[ ] Bug Fix
[ ] Feature
```
Code re-organization, split up into smaller building blocks.
```
[ ] Yes
[x] No
```
=> refactor: extract synthetic ts source handling

package.json, src/lib/ts/ng-type-guards.spec.ts, src/lib/ts/synthesized-source-file.spec.ts, src/testing/typescript.testing.ts, src/testing/typesript.testing.spec.ts
```
[ ] Bug Fix
[ ] Feature
```
Testing module not included in dist. Kind of like `src/test/(kotlin|java|..)` to store source code that is relevant to testing only.
```
[ ] Yes
[x] No
```
=> test: extract testing module to help tests and test testing

src/lib/commands/build.command.ts, src/lib/ng-v5/packagr.spec.ts, src/lib/ng-v5/packagr.ts, src/lib/ts/default-tsconfig.ts
```
[ ] Bug Fix
[x] Feature
```
Closes #557
```
[ ] Yes
[x] No
```
=> feat: expand api w/ `.forProject(string)`,`.withTsConfig(string|TsConfig)`

src/lib/flatten/umd-module-id-strategy.spec.ts, src/lib/flatten/umd-module-id-strategy.ts
```
[x] Bug Fix
[ ] Feature
```
Closes: #579
```
[ ] Yes
[x] No
```
=> fix: map `rxjs/util/*` to its UMD module ID by default

README.md, docs/DESIGN.md, integration/samples/language-level/ng-package.json, integration/samples/language-level/package.json, integration/samples/language-level/public_api.ts, integration/samples/language-level/src/angular.component.ts, integration/samples/language-level/src/angular.module.ts, src/lib/model/ng-package-data.ts, src/lib/steps/ngc.ts, src/ng-package.schema.json
```
[ ] Bug Fix
[X] Feature
```
This PR back ports changes made in #486 to version 1 of the library.
```
[ ] Yes
[X] No
```
=> feat: back porting language level support for library authors

src/lib/ng-v5/entry-point/write-package.transform.ts
Const in a method are not usually camel cased.
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> style: rename const

src/ng-package.schema.json
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> style: fix typo

src/lib/ts/synthesized-compiler-host.ts
Closes #473
```
[x] Bug Fix
[ ] Feature
```
Closes #473 
```
[ ] Yes
[x] No
```
=> fix: return redirect target of typescript source file

src/lib/ng-v5/entry-point/resources/stylesheet.transform.ts
```
[ ] Bug Fix
[ ] Feature
```
Improve postcss rendering. Create the processor for an entry point and re-use it for every stylesheet node of that entry point.
```
[ ] Yes
[x] No
```
=> perf: re-use postcss processor instance per entry point

package.json, src/lib/util/log.ts, tsconfig.json
```
[x] Bug Fix
[ ] Feature
```
Added `chalk` as `dependency`
Closes: #646
```
[ ] Yes
[ ] No
```
=> fix: add `chalk` to dependencies

package.json, src/cli/main.ts, src/lib/commands/version.command.ts, yarn.lock
```
[ ] Bug Fix
[x] Feature
```
adds update-notifier https://github.com/yeoman/update-notifier
adds read-pkg-up instead of custom function https://github.com/sindresorhus/read-pkg-up
closes #639
```
[ ] Yes
[x] No
```
=> feat: add update notifier to cli

src/lib/ts/analyse-dependencies-transformer.ts
Closes: #668
```
[x] Bug Fix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix: cannot read property 'text' of undefined

integration/samples/comments-remove/specs/umd.ts, integration/samples/comments/ng-package.json, integration/samples/comments/specs/umd.ts, src/lib/flatten/flatten.ts, src/lib/flatten/rollup.ts, src/lib/ng-package-format/entry-point.ts, src/lib/ng-v5/entry-point/write-bundles.transform.ts, src/ng-package.schema.json
```
[ ] Bug Fix
[x] Feature
```
Adding support for amd id as per https://github.com/dherges/ng-packagr/issues/673
```
[ ] Yes
[x] No
```
=> feat: add support for amd id in umd bundles

integration/samples/comments-remove/specs/umd.ts, integration/samples/comments/ng-package.json, integration/samples/comments/specs/umd.ts, src/lib/ng-package-format/entry-point.ts, src/lib/ng-v5/entry-point/write-bundles.transform.ts, src/ng-package.schema.json
```
[ ] Bug Fix
[x] Feature
```
#430 
```
[ ] Yes
[x] No
```
=> feat: allow to override umd module identifier

src/lib/flatten/rollup.ts, src/lib/ng-v5/discover-packages.ts, src/lib/ng-v5/entry-point.di.ts, src/lib/ng-v5/entry-point.transform.ts, src/lib/ng-v5/entry-point/relocate-source-maps.di.ts, src/lib/ng-v5/entry-point/relocate-source-maps.transform.ts, src/lib/ng-v5/entry-point/resources/stylesheet.di.ts, src/lib/ng-v5/entry-point/resources/template.di.ts, src/lib/ng-v5/entry-point/resources/template.transform.ts, src/lib/ng-v5/entry-point/ts/compile-ngc.di.ts, src/lib/ng-v5/entry-point/ts/transform-sources.di.ts, src/lib/ng-v5/entry-point/ts/transform-sources.transform.ts, src/lib/ng-v5/entry-point/write-bundles.di.ts, src/lib/ng-v5/entry-point/write-bundles.transform.ts, src/lib/ng-v5/entry-point/write-package.di.ts, src/lib/ng-v5/entry-point/write-package.transform.ts, src/lib/ng-v5/init/analyse-sources.di.ts, src/lib/ng-v5/init/analyse-sources.transform.ts, src/lib/ng-v5/init/init-tsconfig.di.ts, src/lib/ng-v5/init/init-tsconfig.transform.ts, src/lib/ng-v5/nodes.ts, src/lib/ng-v5/package.di.ts, src/lib/ng-v5/packagr.ts, src/lib/sourcemaps/relocate.ts, src/lib/ts/ng-component-transformer.ts, src/lib/ts/transform-component.spec.ts, src/lib/ts/tsconfig.ts
```
[ ] Bug Fix
[ ] Feature
```
The codebase an unbelievable amount of unused imports.
The PR cleans this up.
```
[ ] Yes
[ ] No
```
=> refactor: remove unused imports

src/lib/ng-v5/entry-point/write-package.transform.ts
```
[x] Bug Fix
[ ] Feature
```
See #719 
```
[ ] Yes
[x] No
```
=> fix: don't verify devDependencies in dist-ready package.json

README.md
```
[ ] Bug Fix
[ ] Feature
```
Hey @dherges, I just wanted to link a talk I gave at ngVikings, it's like the 2nd version of my talk at NG-BE which you linked in the README already (🙏 thx for that). The intro is similar, but the core part of the talk is to show how ng-packagr works, and how it could be combined with NX workspace for having a demo library.
I also have an [Egghead lesson on ng-packagr](https://egghead.io/lessons/angular-extract-an-angular-module-into-a-separate-library-with-ng-packagr) but didn't link that one as it's a payed video..meaning you need an Egghead subscription.
```
[ ] Yes
[x] No
```
=> docs: add talk at ngVikings

package.json, src/lib/flatten/uglify.ts, yarn.lock
```
[X] Bug Fix
[ ] Feature
```
Closes: #752
```
[ ] Yes
[X] No
```
=> fix: build error `ENOENT: no such file or directory`

package.json, src/lib/flatten/rollup.ts, src/lib/ts/downlevel-transformer.ts, yarn.lock
```
[ ] Bug Fix
[x] Feature
```
Updates tsickle to version >= 0.27.3
Resolves #679
```
[ ] Yes
[x] No
```
=> feat: update tsickle to =>0.27.3, rollup to ^0.57.1 

package.json, yarn.lock
```
[ ] Bug Fix
[ ] Feature
```
add missing `devDependencies` for `@types/uglify-js`
```
[ ] Yes
[x] No
```
=> build: add missing `devDependencies` for `@types/uglify-js`

src/lib/ng-v5/entry-point/write-package.transform.ts
```
[ ] Bug Fix
[ ] Feature
```
Loop is undeeded
```
[ ] Yes
[x] No
```
=> refactor: remove unnecessary loop in `writePackageJson`

src/lib/ts/tsconfig.ts
```
[x] Bug Fix
[ ] Feature
```
@dherges : tell me if you think some more tests are needed for this.
Setting a custom tsconfig lead to errors if some options are not set, especially when using
the programmatic API.
This commit add some default values and refactor the tsconfig overriding in order to fix this.
```
[ ] Yes
[x] No
```
=> fix: missing options when setting custom tsconfig

integration/samples/material/bar/index.ts, integration/samples/material/public_api.ts, src/lib/ts/downlevel-transformer.ts
```
[x] Bug Fix
[ ] Feature
```
Add moduleResolution to downleveling options
Closes: #784
```
[ ] Yes
[x] No
```
=> fix: cannot resolve `index.js` files

.travis.yml
```
[ ] Bug Fix
[ ] Feature
```
Travis CI will run on node 10, 9, 8. Allow build failure on node 10 due to upath not being compatible
```
[ ] Yes
[ ] No
```
=> ci: resolve travis build errors

src/lib/ng-v5/package.transform.ts
```
[ ] Bug Fix
[ ] Feature
[ c Other (Refactoring, Added tests, Documentation, ...)
```
```
[ ] Yes
[ ] No
```
=> refactor: remove unused method

src/lib/ng-v5/entry-point/write-package.transform.ts
```
[x] Bug Fix
[ ] Feature
```
Version2 bugfix: generate one tarball per npm package
```
[ ] Yes
[x] No
```
=> fix: generate tarball only for primary entry point (one per npm package)

renovate.json
```
[ ] Bug Fix
[ ] Feature
```
Closes: #879
```
[ ] Yes
[x] No
```
=> ci: fix renovate configuration

src/lib/ng-v5/entry-point/write-bundles.transform.ts
```
[ ] Bug Fix
[ ] Feature
```
clean up some code and fix typo
```
[ ] Yes
[x] No
```
=> refactor: clean up `writeBundlesTransform`

docs/DESIGN.md
```
[ ] Bug Fix
[ ] Feature
```
Found that the link to the integration samples was broken in the DESIGN.md  Updated the link to point to the integration samples directory
```
[ ] Yes
[x] No
```
=> docs: fixes path for integration samples link

src/lib/ng-v5/discover-packages.ts
Backports https://github.com/dherges/ng-packagr/pull/930 to V3
=> perf: speed up discovery of secondary entry points (V3)

README.md, docs/dependencies-whitelisting.md, docs/embed-assets-css.md, docs/language-level.md, docs/override-tsconfig.md, docs/style-include-paths.md
```
[ ] Bug Fix
[ ] Feature
```
a documentation on how to override a tsconfig
```
[ ] Yes
[ ] No
```
=> docs: how to

README.md, docs/entry-file.md
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: extract entry file documentation

src/ng-package.schema.json
```
[ ] Bug Fix
[ ] Feature
[x] Other (Documentation fix)
```
There was a typo in ng-package.schema.json, and I fixed it
```
[ ] Yes
[x] No
```
=> docs: fix typo in ng-package.schema.json

docs/embed-assets-css.md
=> docs: add more content for embed assets in css

.appveyor.yml
Added appveyor configuration.
What needs to be done is create an account and authorise it and hope it works :)
Closes: #962
=> ci: add `.appveyor.yml` initial config

integration/watch/basic.spec.ts, integration/watch/basic/secondary/package.json, integration/watch/basic/secondary/public_api.ts, integration/watch/basic/secondary/src/secondary.component.ts, integration/watch/basic/secondary/src/secondary.module.ts, integration/watch/basic/test_files/secondary-valid/secondary/src/secondary.component.ts, integration/watch/test-harness.ts, package.json
Add more tests for incremental builds
=> test: add watch test secondary entry points

integration/samples/scss-paths/.browserslistrc, integration/samples/scss-paths/baz/baz.component.scss, integration/samples/scss-paths/specs/metadata.ts, src/lib/ng-v5/entry-point/resources/stylesheet.transform.ts
```
[x] Bug Fix
[ ] Feature
```
`filePath` is not a valid option. The correct one is `path`
https://www.npmjs.com/package/browserslist#js-api
Closes: angular/angular-cli#11480
```
[ ] Yes
[x] No
```
=> fix: browserlist configuration is not being picked up (v3)

integration/samples/scss-paths/.browserslistrc, integration/samples/scss-paths/baz/baz.component.scss, integration/samples/scss-paths/specs/metadata.ts, src/lib/ng-v5/entry-point/resources/stylesheet-processor.ts
```
[x] Bug Fix
[ ] Feature
```
`filePath` is not a valid option. The correct one is `path`
https://www.npmjs.com/package/browserslist#js-api
Closes: angular/angular-cli#11480
```
[ ] Yes
[x] No
```
=> fix: browserlist configuration is not being picked up (v4)

package.json, yarn.lock
=> fix: update autoprefixer to ^9.0.0, browserslist to ^4.0.0

package.json, yarn.lock
remove unused dependency `@types/strip-bom`
=> refactor: remove unused dependency `@types/strip-bom`

src/lib/ng-v5/package.transform.ts
refactor: make `scheduleEntryPoints` more reactive
=> refactor: make `scheduleEntryPoints` more reactive

integration/watch/basic.spec.ts, integration/watch/basic/test_files/new-file/dummy.ts, src/lib/ng-v5/package.transform.ts
```
[x] Bug Fix
[ ] Feature
```
Sometimes this error is appearing `EmptyError: no elements in sequence`
```
[ ] Yes
[x] No
```
=> fix: no elements in sequence error

package.json, yarn.lock
```
[x] Bug Fix
[ ] Feature
```
Updates Node Sass to v4.9.3 which removes vulnerability warnings while installing the package
```
[ ] Yes
[x] No
```
=> fix: update node-sass to v4.9.3

.appveyor.yml
No need to build branch + PR. only build PR
=> ci: appveyor skip tags and skip branch with pr

src/lib/ng-v5/entry-point/resources/stylesheet-processor.ts
```
[x] Bug Fix
[ ] Feature
```
#1056 
```
[ ] Yes
[x] No
```
=> fix: make css grid transform the default for autoprefixer

integration/samples/scss-paths/baz/baz.component.sass, integration/samples/scss-paths/baz/baz.component.scss, integration/samples/scss-paths/baz/baz.component.ts, integration/samples/scss-paths/baz/baz.theme2.sass, integration/samples/scss-paths/specs/metadata.ts, integration/samples/scss-paths/sub-module/bar/bar.component.sass, integration/samples/scss-paths/sub-module/bar/bar.component.ts, src/lib/ng-v5/entry-point/resources/stylesheet-processor.ts
```
[x] Bug Fix
[ ] Feature
```
separate compilation for scss and sass (indented) syntax
closes #1052 
```
[ ] Yes
[x] No
```
=> fix: allow sass indexed syntax to be compiled (+ integration tests)

README.md, package.json
```
[ ] Bug Fix
[ ] Feature
```
- Updated repo links in package.json
- update links in README.md
issuestats seems to be down. `travis` badges doesn't show status, since migration is not done.
```
[ ] Yes
[x] No
```
=> docs: update repo links

.circleci/config.yml, package.json
```
[ ] Bug Fix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat: add `TypeScript` version 3 as a `peerDependency`

yarn.lock
in the hope to cause conflicts so that renovate re trigger all prs
=> build: regenerate lock file

src/lib/ng-v5/entry-point/write-package.transform.ts
```
[ ] Bug Fix
[ ] Feature
```
Fixed few typos
```
[ ] Yes
[x] No
```
=> chore: fix typos in comments

package.json
Angular 7 RC.0 requires TypeScript 3.1+
=> feat: add support for TypeScript 3.1

src/lib/ng-v5/discover-packages.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: ignore git folder on watch

.circleci/config.yml
```
[ ] Bug Fix
[ ] Feature
```
Update Circle CI Workflows.
This separates deployment as a separate workflow and runs only on master branch with tagged commits.
```
[ ] Yes
[x] No
```
=> ci: update circle-ci workflows

README.md
It fixes placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [more info](https://github.com/opencollective/opencollective/wiki/Github-banner). See how it looks on this [repo](https://github.com/apex/apex#backers).
You can also add a postinstall script to let people know after npm|yarn install that you are welcoming donations (optional). [More info](https://github.com/OpenCollective/opencollective-cli)
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets
P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because …
=> Fix open collective images

package.json
```
[ ] Bug Fix
[x] Feature
```
Angular 7.2 added support for TypeScript 3.2
```
[ ] Yes
[x] No
```
=> feat: add support for TypeScript 3.2

src/lib/brocc/node.ts, src/lib/ng-v5/init/analyse-sources.transform.ts, src/lib/ng-v5/nodes.ts, src/lib/ng-v5/package.transform.ts, src/lib/ngc/compile-source-files.ts, src/lib/ts/cache-compiler-host.ts
```
[ ] Bug Fix
[ ] Feature
```
- Caching ng program improve the performance of incremental compilations.
- perf: improve entry points analyses by using better compiler options
```
[ ] Yes
[X] No
```
=> perf: cache ng program for faster incremental builds

integration/samples/secondary/feature-c/index.ts, integration/samples/secondary/feature-c/package.json, src/lib/ng-v5/init/analyse-sources.transform.ts, src/lib/ng-v5/nodes.ts, src/lib/ng-v5/package.transform.ts, src/lib/ngc/compile-source-files.ts, src/lib/ts/cache-compiler-host.ts
Fixes #1183
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: analyses of secondary entrypoints doesn't work with deep imports

src/lib/ng-v5/init/analyse-sources.transform.ts
=> fix: use old TypeScript API to support users which are still on 2.7.x+

package.json, src/lib/ngc/create-emit-callback.ts, yarn.lock
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat: add support for tsickle to 0.34.0

package.json, yarn.lock
```
[x] Bug Fix
[ ] Feature
```
fixes issue https://github.com/ng-packagr/ng-packagr/issues/1178
replaces PR https://github.com/ng-packagr/ng-packagr/pull/1182
see also https://github.com/opencollective/opencollective-postinstall/issues/15
```
[ ] Yes
[x] No
```
=> Replace opencollective-cli with opencollective-postinstall

src/lib/ng-v5/init/analyse-sources.transform.ts
Don't uses classic module resolution instead, resolve only relative imports.
Fixes #1210
=> fix: don't use classic module resolution during analyse

src/lib/ngc/compile-source-files.ts
At the moment we are not emitting information diagnostics and also diagnostics emitted during the compilation
=> fix: emit complete diagnostics

src/lib/ng-v5/package.transform.ts
```
[ ] Bug Fix
[ ] Feature
```
We only need to delete direct dependencies when changing a resource file such as html and css.
This should increase the performance on larger projects with a more complex dependency graph.
```
[ ] Yes
[ ] No
```
=> perf: reduce the amount of dependees that are removed

package.json
feat: add support for Angular 8 and TypeScript 3.3
=> feat: add support for Angular 8 and TypeScript 3.3

README.md
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[X] No
```
=> docs: add install section to readme

package.json
```
[ ] Bug Fix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat: add support for TypeScript 3.4

src/lib/ng-v5/package.transform.ts
In a monorepo certain files may be softlinked. This change will make sure the  
links are dereferenced and the created files have the correct contents.
```
[x] Bug Fix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix: copy+dereference LICENSE and README.md

src/lib/ng-v5/entry-point/ts/compile-ngc.transform.ts, src/lib/ng-v5/packagr.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: don't write stacktraces when there are errors

README.md, package.json, yarn.lock
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: remove opencollective postinstall scripts

integration/samples/scss-paths/baz/baz component.less, src/lib/ng-v5/entry-point/resources/stylesheet-processor.ts
```
[ ] Bug Fix
[x] Feature
```
- Technically no new tests, but the integration sample was expanded to include inline javascript in its less styling.
Less is executed allowing inline javascript. Fixes #1298 
```
[ ] Yes
[X] No
```
=> feat: support inline javascript in less

package.json, src/lib/ng-v5/entry-point/resources/stylesheet-processor.ts, yarn.lock
=> refactor: use new autoprefixer API

.appveyor.yml
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> ci: remove PATH from appveyor config

package.json
Relates to https://github.com/angular/angular/pull/31615
=> feat: add support for typescript 3.5 and Angular 8.X pre-releases

integration/samples/typings/ng-package.json, src/lib/ng-package-format/entry-point.ts, src/ng-package.schema.json
=> fix: handle deep undefined in schema options

src/lib/ng-package-format/entry-point.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> refactor: entry point `$get` to be more safe

integration/samples/custom/specs/metadata.ts, integration/samples/custom/src/baz/baz.component.html, integration/samples/custom/src/baz/baz.component.svg, integration/samples/custom/src/baz/baz.component.ts, src/lib/ts/cache-compiler-host.ts
```
[x] Bug Fix
[ ] Feature
```
Closes: https://github.com/angular/angular-cli/issues/15187
=> fix: handle svg templates same as html files

src/lib/flatten/uglify.ts
Most of these errors are not actionable as they remove code which was generated by either tsickle of ngc.
Closes: #1177 and closes #1394
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: remove terser warnings as these as not actionable

src/lib/ng-v5/package.transform.ts
```
[ ] Bug Fix
[x ] Feature
```
Optionally copy 'CHANGELOG.md' to dist folder
https://github.com/ng-packagr/ng-packagr/issues/347
```
[ ] Yes
[x] No
```
=> feat: copies `CHANGELOG.md` to package destination

integration/samples/apf/specs/package.ts, package.json, src/lib/ng-v5/entry-point/write-package.transform.ts, src/lib/ngc/ngcc-processor.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> Angular version 9

src/lib/ngc/ngcc-processor.ts
Related to https://github.com/angular/angular-cli/pull/16000
=> fix: skip NGCC when file system is read only

src/lib/ng-v5/init/init-tsconfig.transform.ts
Closes #1453
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: add link to Angular guide when showing ivy publish warning

integration/samples/typings/src/validator.ts, package.json, src/lib/ng-v5/init/init-tsconfig.transform.ts, src/lib/util/log.ts, yarn.lock
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: update chalk to v3

src/lib/ng-v5/entry-point/write-package.transform.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: ignore `.gitkeep`, `Thumbs.db` and `.DS_Store` when copying files

.circleci/config.yml
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> ci: cache yarn cache

.circleci/config.yml
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> ci: optimize persist_to_workspace in build_and_test

src/lib/ngc/create-emit-callback.ts
Reverts ng-packagr/ng-packagr#1489
=> Revert "Ignore JSON files in tsickle processing"

src/lib/ng-package/entry-point/analyse-sources.di.ts, src/lib/ng-package/entry-point/analyse-sources.transform.ts, src/lib/ng-package/entry-point/init-tsconfig.di.ts, src/lib/ng-package/entry-point/init-tsconfig.transform.ts, src/lib/ng-package/package.di.ts, src/lib/packagr.spec.ts, src/lib/packagr.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> style: move analyses and init-tsconfig

src/lib/ng-package/package.transform.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: reset glob cache on file add

src/lib/ng-package/nodes.ts, src/lib/ng-package/package.transform.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> perf: re-populate glob cache

src/lib/ng-package/entry-point/analyse-sources.transform.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: analyse only non done entry points

integration/samples/secondary/feature-a/feature-a.ts, src/lib/ng-package/entry-point/analyse-sources.transform.ts
Closes #1508
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: circular dependency on itself error

src/lib/ng-package/entry-point/analyse-sources.transform.ts
=> fix: incorrect detection of potential dependent entry-points

src/lib/ng-package/entry-point/analyse-sources.transform.ts, src/lib/ng-package/nodes.ts, src/lib/ts/cache-compiler-host.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: analyse sources transform

src/lib/ng-package/discover-packages.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: show schema errors

src/lib/ng-package/entry-point/analyse-sources.transform.ts
=> fix: throw error on circular dependencies

src/lib/flatten/umd-module-id-strategy.spec.ts, src/lib/flatten/umd-module-id-strategy.ts, src/lib/utils/strings.ts
Fixes https://github.com/angular/angular/issues/35765
=> fix: wrong UMD ID's of Angular packages with a dash in name

package.json
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat: add support for TypeScript 3.8

integration/consumers/ng-cli/angular.json, integration/consumers/ng-cli/browserslist, integration/consumers/ng-cli/package.json, integration/consumers/ng-cli/src/app/secondary/secondary.component.ts, integration/consumers/ng-cli/src/tsconfig.app.json, integration/consumers/ng-cli/src/tsconfig.spec.json, integration/consumers/ng-cli/tsconfig.json, integration/consumers/ng-cli/yarn.lock, integration/samples/material/foo/foo.component.ts, integration/samples/secondary/feature-a/feature-a.ts, renovate.json
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> test: update angular version in consumers app

docs/embed-assets-css.md
Just a fixing minor typos and some grammar in the documentation.
```
[ ] Bug Fix
[ ] Feature
[*] Other (Refactoring, Added tests, Documentation, ...)
```
Some minor fixes to the documentation, no structural change.
```
[ ] Yes
[*] No
```
=> docs: correct minor typos

src/lib/file-system/file-watcher.ts
Closes #1583
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> perf: ignore node_modules from file watching

.prettierrc, src/lib/ng-package/entry-point/analyse-sources.transform.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> perf: use endsWith instead of complex RegExp during dependency analysis

package.json
```
[ ] Bug Fix
[ ] Feature
```
fix release commit message formatting https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/1.0.0/README.md#releasecommitmessageformat-string
```
[ ] Yes
[x] No
```
=> fix: release commit message formatting

package.json, src/lib/flatten/uglify.ts, yarn.lock
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: update terser to version 5.0.0

src/lib/flatten/external-module-id-strategy.ts, src/lib/graph/transform.di.ts, src/lib/graph/transform.ts, src/lib/ng-package/entry-point/entry-point.ts, src/lib/ng-package/entry-point/write-bundles.transform.ts, src/lib/ng-package/entry-point/write-package.transform.ts, src/lib/ng-package/package.ts, src/lib/ngc/create-emit-callback.ts, src/lib/packagr.ts
```
[ ] Bug Fix
[ ] Feature
```
Fixed some spelling errors inside comments.
```
[ ] Yes
[x] No
```
=> docs: fix spelling errors

src/lib/styles/stylesheet-processor.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: fix windows less spawn error

package.json, yarn.lock
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: remove unused dependencies

package.json, src/lib/ng-package/entry-point/compile-ngc.transform.ts, src/lib/ng-package/entry-point/write-bundles.transform.ts, src/lib/ng-package/entry-point/write-package.transform.ts, yarn.lock
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat: improve progress reporting

src/lib/ts/tsconfig.ts
Reverts ng-packagr/ng-packagr#1786
=> Revert "fix: sourcemap should not differ based on build path"

package.json, yarn.lock
Reverts ng-packagr/ng-packagr#1778
=> revert: "fix: update @rollup/plugin-commonjs to version ^16.0.0"

integration/samples/core/specs/sourcemaps.ts, src/lib/ts/tsconfig.ts
Closes https://github.com/angular/angular-cli/issues/19456
=> fix: correctly resolve sourceRoot

src/lib/ng-package/entry-point/compile-ngc.transform.ts, src/lib/ng-package/entry-point/write-bundles.transform.ts, src/lib/ng-package/entry-point/write-package.transform.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: termination of process when using CTRL+C

package.json
=> fix: add tsickle as optional peer dependency

integration/samples/api/specs/sourcemaps.ts, integration/samples/api/tsconfig.ngc.json, integration/samples/core/specs/sourcemaps.ts, src/lib/ts/tsconfig.ts
Closes https://github.com/angular/angular-cli/issues/19668
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: set sourceRoot to empty string to correctly resolve dts sources

src/lib/ng-package/entry-point/write-package.transform.ts, src/lib/ng-package/package.transform.ts
Closes #1826
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix:  changed assets not being copied during watch mode

src/lib/ng-package/entry-point/analyse-sources.transform.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> refactor: use source file isDeclarationFile instead of endsWith

src/lib/graph/node.ts, src/lib/graph/select.ts, src/lib/ng-package/package.transform.ts, src/lib/styles/stylesheet-processor.ts
```
[ ] Bug Fix
[ ] Feature
```
Fixed spelling error in variable names, the public one was not removed, it's now deprecated.
```
[ ] Yes
[x] No
```
=> refactor: fix spelling errors in variable names

src/lib/styles/stylesheet-processor-worker.ts, src/lib/styles/stylesheet-processor.ts
Closes #1867
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: use `path.join` instead of `require.resolve` to resolve worker

src/lib/ng-package/entry-point/write-package.transform.ts
Closes #1883
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: replace `i` with checkmark when displaying a built entrypoint

src/lib/ng-package/package.ts, src/ng-package.schema.json
```
[X] Bug Fix
[ ] Feature
```
Ref: https://github.com/ng-packagr/ng-packagr/issues/1892
Removed the default value from deprecated property `whitelistedNonPeerDependencies` in the json schema.
```
[ ] Yes
[X] No
```
=> fix: removed default value from whitelistedNonPeerDependencies in json schema

integration/samples/custom/ng-package.json, package.json, src/lib/ng-package/discover-packages.ts, yarn.lock
=> feat: add support for comments in JSON configuration file

src/lib/styles/stylesheet-processor-worker.ts, src/lib/styles/stylesheet-processor.ts
Currently the main thread remains blocked when the there is an error in the worker.
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: release main thread on worker error

src/lib/ngc/compile-source-files.ts
We no longer support TS 4.0, hence this check is redudant.
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=>  refactor: remove TypeScript 4.0 program reuse check

src/lib/graph/build-graph.ts, src/lib/graph/node.ts, src/lib/ng-package/package.transform.ts, src/lib/utils/array.ts, src/lib/utils/glob.ts
- use Sets instead of Arrays in Nodes for faster lookups
- Use flatMap instead of flatten
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> refactor: several code improvements

src/lib/styles/stylesheet-processor-worker.ts
With this change we improve the rendered CSS mechanism to cache more aggressivly if the contents don't include `@use` or `@import`.
We also fix the `package.json` path which caused hanging builds.
Closes https://github.com/angular/angular-cli/issues/20726
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: improve stylesheet caching mechanism

src/lib/ts/cache-compiler-host.ts
Closes #1983
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: log error from stylesheet pre-processor

src/lib/ng-package/entry-point/analyse-sources.transform.ts
Closes #1982
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: ignore type definitions when building entry-point dependency graph

package.json
```
[x] Bug Fix
[ ] Feature
```
This is to align the supported nodejs versions with [angular/cli v12.0.3](https://github.com/angular/angular-cli/releases/tag/v12.0.3).
```
[ ] Yes
[x] No
```
=> fix: update supported range of node versions

src/lib/ng-package/entry-point/compile-ngc.transform.ts
=> feat: add compilation mode in build logs

src/lib/ng-package/entry-point/entry-point.transform.ts, src/lib/styles/stylesheet-processor-worker.ts
Closes: https://github.com/angular/angular-cli/issues/21335
=> fix: parse styles cache as JSON

src/lib/ivy/styles/stylesheet-processor.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: provide supported browsers to esbuild

src/lib/styles/stylesheet-processor.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: improve Safari browserslist to esbuild target conversion

package.json, src/lib/esbuild/esbuild-check.js, src/lib/esbuild/esbuild-executor.ts, src/lib/styles/stylesheet-processor.ts, yarn.lock
See: angular/angular-cli#21687
=> fix: support WASM-based esbuild optimizer fallback

src/lib/flatten/downlevel-plugin.ts, src/lib/ng-package/entry-point/compile-ngc.transform.ts, src/lib/ng-package/entry-point/write-bundles.transform.ts, src/lib/ng-package/options.di.ts, src/lib/packagr.ts, src/lib/styles/stylesheet-processor.ts, src/lib/utils/cache.ts
With this change we add `cacheEnabled` and `cacheDirectory` options to make cache more configurable.
=> feat: enable providing cache directory and disabling caching via options

integration/samples/apf/specs/package.ts, src/lib/ng-package/entry-point/entry-point.spec.ts, src/lib/ng-package/entry-point/entry-point.ts, src/lib/ng-package/entry-point/write-package.transform.ts
With this change exports field will be included in the package.json of the library.
=> feat: add support for package.json exports

integration/samples/apf/specs/files.ts, integration/samples/apf/specs/package.ts, integration/samples/core/specs/package.ts, integration/samples/core/specs/sourcemaps.ts, integration/samples/custom/specs/package.ts, integration/samples/inline-style-language/specs/build.ts, integration/samples/issue-1451/specs/license.ts, integration/samples/ivy/specs/files.ts, integration/samples/keep-output-path/.gitignore, integration/samples/material/specs/package.ts, integration/samples/same-name/specs/package.ts, integration/samples/secondary/specs/ep-feature-a.ts, integration/samples/secondary/specs/ep-feature-b.ts, integration/samples/secondary/specs/ep-feature-d.ts, integration/samples/secondary/specs/ep-shared.ts, integration/watch/intra-dependent.spec.ts, integration/watch/test-harness.ts, src/lib/file-system/file-watcher.ts, src/lib/ng-package/entry-point/entry-point.ts, src/lib/ng-package/entry-point/write-package.transform.ts, src/lib/ts/cache-compiler-host.ts
With this change we emit the files in mjs format.
=> feat: emit Javascript files with `.mjs` extension

integration/samples/apf/package.json, integration/samples/apf/specs/files.ts, integration/samples/apf/specs/package.ts, integration/samples/apf/theming.scss, package.json, src/lib/ng-package/entry-point/write-package.transform.ts, yarn.lock
=> fix: unable to add additional conditions to entry-point subpaths controlled by ng-packagr

src/cli/main.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> Version fix

package.json, yarn.lock
Reverts ng-packagr/ng-packagr#2159
=> Revert "build: update dependency postcss-preset-env to v7"

integration/watch/resources/package.json, src/lib/ng-package/entry-point/write-package.transform.ts
=> fix: package exports merging during watch mode

.husky/commit-msg, .husky/pre-commit, package.json
fix for broken husky v7 hooks
```
[ ] Bug Fix
[ ] Feature
```
This PR fixes broken husky v7 hooks.
Migrated husky v4 style configuration to husky v7 style configuration
Introduced by renovate bot:
- v7 https://github.com/ng-packagr/ng-packagr/commit/80a2ccf267533ef9133ada8b4f3fa14cdf7c8e49
- v6 https://github.com/ng-packagr/ng-packagr/commit/adea21bf6f55fe89bdf9637166a46d379c0dd688
- v5 https://github.com/ng-packagr/ng-packagr/commit/68b6809a9e8448441c2c4f56916cbfbc0b66d4df
```
[ ] Yes
[x] No
```
=> build: fix husky v7 hooks

src/lib/ivy/styles/stylesheet-processor.ts, src/lib/styles/stylesheet-processor.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> Versions lts

src/lib/ng-package/package.ts
=> fix: join paths instead of resolving

src/lib/commands/build.command.ts, src/lib/packagr.ts
Closes https://github.com/ng-packagr/ng-packagr/issues/2300
=> fix: watch mode when using ng-packagr CLI directly

integration/consumers/ng-cli/package.json, integration/consumers/ng-cli/yarn.lock, package.json, src/lib/ng-package/entry-point/analyse-sources.transform.ts, src/lib/ts/ngcc-transform-compiler-host.ts, yarn.lock
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat: support TypeScript 4.7

integration/samples/apf/specs/files.ts, integration/samples/issue-1451/specs/license.ts, src/lib/ng-package/discover-packages.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> test: fix tests to run on Windows

src/lib/ng-package/entry-point/analyse-sources.transform.ts
`index.ts` which are parallel to an `entryFilePath` must be configured set as `entryFilePath` to allow correct resolution.
Closes https://github.com/angular/angular-cli/issues/23293
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: error when index file is parallel to entry-point but is not configured as such

src/lib/ngc/ngcc-processor.ts
Prior to this change, ng-packagr would fail with an error when ngcc could not
be run due to a missing `node_modules` directory, as is the case with Yarn
Plug'n'Play for example. The workaround was to create an empty `node_modules`
directory, but this is inconvenient and shouldn't make any difference.
This commit removes the error and simply skips ngcc processing.
---
This is a mirror of angular/angular-cli#23487
=> fix: do not run ngcc when node_modules does not exist

src/lib/ts/cache-compiler-host.ts
=> fix: address issue were dts were not emitted fully when using entrypoint name as filename

package.json, yarn.lock
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat: add support for TypeScript 4.8

src/lib/ng-package/entry-point/write-package.transform.ts, src/lib/ng-package/package.transform.ts
=> fix: exclude scanning node_modules when trying to locate README.md

integration/samples/ivy/tsconfig.ngc.json, src/lib/ts/tsconfig.ts
Ivy is the only rendering engine.
=> refactor: remove enableIvy check

src/lib/ts/cache-compiler-host.ts
Closes https://github.com/angular/angular-cli/issues/24143
=> fix: show actionable error when component resource is not found

README.md
```
[ ] Bug Fix
[ ] Feature
```
Update instructions to use `ng-package.json`.
```
[ ] Yes
[x] No
```
=> fix usage instructions

README.md
=> docs: remove systemjs reference

src/lib/styles/stylesheet-processor.ts
Prior to this change the `renderWorker` worker was created in an async fashion. In some cases this causes multiple instances of the `renderWorker` which causes, slower builds and sharp increase in memory usage.
Closes #2530
=> perf: create a single stylesheet renderer worker instance

package.json, yarn.lock
Reverts ng-packagr/ng-packagr#2538
=> Revert "build: update dependency esbuild-wasm to ^0.17.0"

package.json, yarn.lock
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: update dependency esbuild to ^0.17.0

integration/samples/apf/secondary/README.md, src/lib/ng-package/entry-point/write-package.transform.ts
=> fix: only copy README.md from entry-points

integration/watch/test-harness.ts, src/lib/graph/transform.ts, src/lib/ng-package/entry-point/analyse-sources.transform.ts, src/lib/ng-package/package.transform.ts, src/lib/packagr.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> RXJS imports

src/lib/styles/stylesheet-processor.ts
With this change we added `tailwind.config.mjs` and `tailwind.config.ts` to known tailwind config files.
=> fix: update list of known tailwind configuration files

src/lib/ngc/compile-source-files.ts
=> refactor: replace `incrementalDriver` with `incrementalCompilation`

src/lib/ng-package/entry-point/write-package.transform.ts
=> fix: warn when finding conflicting package export conditions

package.json
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat: support TypeScript 5.1

docs/release.md
```
```
Documenting the release process.
```
[ ] Yes
[X] No
```
=> docs: document release process

package.json
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat: add support for Angular 17

package.json, yarn.lock
Updates the repo to TypeScript 5.2.
=> feat: support TypeScript 5.2

.circleci/config.yml
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> ci: update Node.js version to 18

src/lib/styles/stylesheet-processor.ts
Workaround until https://github.com/piscinajs/piscina/issues/427 is released
Closes #2688
=> fix: add workaround to terminate workers on destroy

package.json, yarn.lock
Bumps the repo to TypeScript 5.3.
=> build: update to TypeScript 5.3

src/lib/ng-package/entry-point/write-bundles.transform.ts, src/lib/ng-package/nodes.ts, src/lib/ts/cache-compiler-host.ts
With this change during watch mode, only the changed files will be rewritten from the NG compiler.
=> perf: only emit changed DTS and JS from NG compiler

integration/samples/embed-assets/specs/component-embed.ts, src/lib/styles/stylesheet-processor-worker.ts
=> fix: correctly embed CSS resources

integration/watch/basic.spec.ts, src/lib/ng-package/entry-point/write-package.transform.ts
Reverts ng-packagr/ng-packagr#2740
Closes #2773
=> Revert "perf: do not update package.json version on watch mode"

integration/samples/embed-assets/src/angular.component.scss, src/lib/styles/css-resource-plugin.ts, src/lib/styles/stylesheet-processor-worker.ts
Closes https://github.com/angular/angular-cli/issues/27037
=> fix: handle absolute `url` reference in CSS files

package.json, yarn.lock
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat: add support for Angular 18

integration/samples/apf/specs/files.ts, integration/samples/apf/specs/package.ts, integration/samples/issue-1451/specs/license.ts, package.json, src/lib/flatten/file-loader-plugin.ts, src/lib/flatten/rollup.ts, src/lib/ng-package/entry-point/write-bundles.transform.ts, src/lib/ng-package/entry-point/write-package.transform.ts, src/lib/ts/cache-compiler-host.ts, yarn.lock
See https://github.com/angular/angular/pull/57559
=> feat: remove unused ESM2022 from APF

package.json, yarn.lock
Updates the project to support TypeScript 5.7.
=> feat: support TypeScript 5.7

package.json, yarn.lock
Updates the repo to allow TypeScript 5.8 that is now supported by the framework.
=> feat: support TypeScript 5.8

src/lib/styles/stylesheets/sass-language.ts
Enhanced Sass integration by adding support for package importers.
See: https://sass-lang.com/blog/announcing-pkg-importers/
=> feat: support Sass package importers

src/lib/graph/build-graph.ts, src/lib/ng-package/nodes.ts, src/lib/ng-package/package.transform.ts
Replaced array with Set to ensure unique node iteration during deletion, improving performance and reducing redundant operations.
=> perf: optimize node deletion using `Set`

src/lib/ng-package/nodes.ts
=> refactor: improve `isEntryPointDirty` and `isEntryPointInProgress` perf

docs/override-tsconfig.md, integration/samples.ts, integration/samples/api/ng-packagr-api.js, integration/samples/ivy/ng-packagr-api.js, integration/watch/test-harness.ts, package.json, scripts/postbuild.js, src/lib/ng-package/schema.ts, src/tsconfig.packagr.json
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: ensure in package `.browserslistrc` is correctly resolved

src/lib/utils/cache.ts
Closes: https://github.com/ng-packagr/ng-packagr/issues/3080
=> fix: prevent 'Unexpected non-whitespace character' error

package.json, pnpm-lock.yaml
Updates the project to TypeScript 5.9.
=> build: support TypeScript 5.9
